### ISSUE TITLE
api: create api for getting / setting slamengine server config

### ISSUE THREAD

**Issue by jdegoes** [slamdata/slamengine#182]
## Set server port

```
PUT /server/port
```

This will restart the server at the specified port. All communication from the client must shift over to the new port.

There is no need for an API to get the server port, since in order to call the API, you would already have to know the port.

## Get all the mount configuration at a specified path

To find out which paths represent mounted data sources, a client can use the metadata API and look for mount resources. This API is to retrieve configuration for a given mount.

```
GET /mounts/fs/[path]
```

A mount is a string which represents an Connection URI.

## Create a new mount configuration at a specified path

For this method to succeed, there must not exist any existing resource (mount or otherwise) at the specified path.

```
POST /mounts/fs/[path]
```

A mount is a string which represents an Connection URI.

## Update an existing mount at a specified path

For this method to succeed, there must exist a mount at the specified path.

```
PUT /mounts/fs/[path]
```

A mount is a string which represents an Connection URI.

## Delete an existing mount at a specified path

```
DELETE /mounts/fs/[path]
```

**Comment by jdegoes** [comment]
The update and create APIs must return errors and warnings in a JSON file format which can be interpreted by the client and rendered to the human who is creating or updating the mounts.

These errors / warnings will be used in the SlamData front-end to guide users into correctly forming the required URI / structure components of the URI.

**Comment by jdegoes** [comment]
On all APIs going forward, let's use the HTTP detailed status message for 1 line error summaries, and the HTTP `Warning` header for warning messages (an HTTP response may contain multiple `Warning` headers). Detailed JSON error / warning messages should be placed in the body using a standardized convention (e.g. `{"errors": [], "warnings": [ ], "value": ..}` or something).

**Comment by sellout** [comment]
And we want these resources to be top-level, not under /config or something?

**Comment by jdegoes** [comment]
Yes, put them all at top level like the rest of the APIs. Compare: `/mounts/fs/foo/`, `/metadata/fs/foo/`, `/query/fs/foo/`, etc.

**Comment by sellout** [comment]
Should `GET /mount/fs/<path>` only return the mount _at_ `path` (if one exists, 404 otherwise), or every mount _under_ `path`?

**Comment by jdegoes** [comment]
It should return the mount configuration exactly at the paths where the metadata API will classify the resource as a "mount". i.e. the former and not the latter.
