### ISSUE TITLE
planner: DISTINCT * does not work

### ISSUE THREAD

**Issue by mossprescott** [slamdata/slamengine#283]
The problem is that every doc has a necessarily unique `_id` field, so DISTINCT will never be able to remove anything. Without knowing the shape, we cannot specify the particular fields to match on.

Furthermore: the aggregation pipeline cannot exclude the _id field, so projecting to a temp name without _id will not work. There may be a workaround involving MapReduce.

See #211.

**Comment by sellout** [comment]
Fixed by #630.
