### ISSUE TITLE
api: add ability to serve static assets

### ISSUE THREAD

**Issue by jdegoes** [slamdata/slamengine#482]
The API should have the ability to serve static assets such as CSS, JS, HTML, PNG, and font files -- any assets which could be required by the SlamData web front-end.

# Checklist

- [x] SlamData Web JAR serves everything in the `./apps/` directory (co-located with the JAR) under the URL `./apps`, with the intention of using the `./apps/slamdata` namespace for the frontend.
- [x] The installers project builds not just the admin tool, but also builds the web application, by downloading the slamdata front-end (pre-built from releases?), and moving it into an `./app/slamdata/` directory co-located with the JAR, where the installer builder will incorporate all assets into the installers.
- [x] The installers project uploads final installers for the web app to Bintray.

**Comment by sellout** [comment]
So, the installer aspect of this somewhat depends on #182. Jeff just discovered that the server won’t start if there’s no existing config file, so we need to allow it to. But to do that, we need to be able to add mountings via the API for it to be useful.

**Comment by jdegoes** [comment]
Makes sense, let's not hold this up on that account, Jeff can re-test after #182.

**Comment by sellout** [comment]
Ok, just realized an aspect of this I missed … we want the installers to include _both_ the admin and web UIs? I just replaced the admin with the web UI.

I can include the admin jar easily … is that enough, or do we need some intelligent way to launch it, etc?

**Comment by jdegoes** [comment]
You can add launchers inside install4j for both the Admin GUI and SlamData.

We want to be very careful with naming since wrong names will confuse users, generate support tickets, and disgruntle @jdegoes : :imp: 

1. We call the Admin GUI the *SlamData Admin Tool*, mostly to scare users away from launching it and being confused at why it doesn't resemble the screenshots.
2. We call the server *SlamData*. The server will launch a browser that points to SlamData, so it's close enough. The users don't need to know the distinction between front-end and back-end.

**Comment by sellout** [comment]
This was fixed by #706.
