### ISSUE TITLE
config: REPL, admin GUI, and API should read config file from default location

### ISSUE THREAD

**Issue by mossprescott** [slamdata/slamengine#505]
Currently, the REPL and API both use `DefaultConfig` if no config file location is specified, whereas the Admin UI looks for (and writes) the file in a standard location under the user's directory (based on the platform).

See:
- https://github.com/slamdata/slamengine/blob/master/core/src/main/scala/slamdata/engine/repl/repl.scala#L256
- https://github.com/slamdata/slamengine/blob/master/core/src/main/scala/slamdata/engine/api/server.scala#L19
- https://github.com/slamdata/slamengine/blob/master/admin/src/main/scala/slamdata/engine/admin/admin.scala#L30

All three should use the same location, so you can use the Admin tool to set up and then use the other tools without hassle.

- [ ] Move the code somewhere common (config.scala?)
- [ ] Use it in all three tools
- [ ] Document in README.md

**Comment by sellout** [comment]
I think there are currently three config sources (in order of preference):

1. `$SLAMDATA_MONGODB`,
2. a file (either specified or the system-specific default), and
3. `Config.DefaultConfig`.

If there’s an existing file, the Admin UI loads/edits that, which makes sense. If there’s no existing file, then should we initialize the file with `Config.DefaultConfig`? And finally, if `$SLAMDATA_MONGODB` is specified … should we just handle the config in memory?

Also, should `Config.DefaultConfig` go away? Connecting everyone to our MongoLab account by default doesn’t seem particularly helpful.

**Comment by jdegoes** [comment]
The first one is not a config source. Rather, I believe it is used in integration tests for backends. In fact, I think it's generic, SLAMDATA_[backend], that is, MongoDB is not hard coded, so environment variables can be used to specify or override integration test config for any backend. That's unrelated to configuration for REPL, Admin, and API.

Config.DefaultConfig is really only for our own benefit. We connect the REPL to that, which makes it easier for testing. Probably we need to push that into sbt so when we run the REPL it can pull configuration from there. 

In any case, I don't think standalone REPL, Admin GUI, or Web API should have any "default config". They should have a default place they look for the config, and all three tools should look in the same place. That's what this ticket is about -- sharing the same configuration file / location across all 3 tools that require it.
