### ISSUE TITLE
mongodb: support way to create oid from string

### ISSUE THREAD

**Issue by jdegoes** [slamdata/slamengine#537]
- [ ] Add unary `ID` operator to parser and SQL AST.
 - [ ] Add `MAKE_ID` or some such function to the standard library (need to find a good way to organize it).
 - [ ] Add an `Id` type to `Type` and update the type checking functions / rest of the code base to deal with this new type.
 - [ ] Implement `MAKE_ID` for the MongoDB planner and document the implementation.

**Comment by mossprescott** [comment]
What's the intention here? Are we trying to support queries on _id?

Assuming "oids" always have a string representation, we could have a generic `OID` operator, similar to `TIMESTAMP`, which takes a string and turns it into whatever the backend's representation of an oid happens to be. As in `select * from aTable where _id = OID '1234567'`. Does that cover the use case?

A related question is how these values are represented in JSON on the way out. See #255.

**Comment by jdegoes** [comment]
Upon further reflection, it seems adding a unary `ID` function similar to `TIMESTAMP` etc. functions, which creates an id from a string, might be helpful, since different backends will have different notions of what constitutes an id.

There are several steps involved here:

[ ] Add unary `ID` operator to parser and SQL AST.
[ ] Add `MAKE_ID` or some such function to the standard library (need to find a good way to organize it).
[ ] Add an `Id` type to `Type` and update the type checking functions / rest of the code base to deal with this new type.
[ ] Implement `MAKE_ID` for the MongoDB planner and document the implementation.

**Comment by mossprescott** [comment]
One issue with this is that `ID` is a fairly commonly-used identifier, so I'm not sure we want to make it a keyword. For example, the obvious use is `select _id as id, ...`.

 There seems to be some consensus around `OID` (PostgreSQL use it, and MongoDB of course uses the longer ObjectId), which is why I initially suggested that instead. What do you think, @jdegoes?

**Comment by jdegoes** [comment]
If Postgres uses it, then `OID` it is. 

I do think the real solution to these problems is to relax the parser. There's no reason something can't be both a operator and an identifier if the context always makes it clear, and for unary operators, the context always makes it clear (there's just one globally unambiguous way to parse them).

Some people will want to call this field `oid`, which of course will clash again with the unary operator of the same name. Same for `TIMESTAMP`, etc., which are very common names.

The existing restrictions in ANSI SQL come from antiquated parsers without arbitrary backtracking capability.

**Comment by mossprescott** [comment]
Even if we made the parser smarter, I think humans would likely be confused by a syntax that allowed identifiers and unary operators with the same names (or, more likely, by the error messages that would result from using them incorrectly). We're getting away with that for functions, but mostly because of the mandatory parens, I guess.

Parsing sucks.

**Comment by jdegoes** [comment]
Actually, humans are extremely good at this sort of ambiguity (see also: the English language and every other language in the world). It crops up in math all the time, e.g. `-9 * 2 - 5`, which reuses the `-` operator for both unary negation and subtraction.

SQL blunderingly monopolizes keywords that are extremely common field names (including, `COUNT`, `SUM`, etc., and `TIME`, `DATE`, etc.), leading to confusion in SQL newbies as they wonder why their seemingly valid query barfs with strange error messages.

Definitely a problem I intend to rectify.

**Comment by mossprescott** [comment]
I don't entirely agree, but I don't see much point in arguing it.

One nice thing I just noticed: you *can* use function names as identifiers where an expression is not expected:
```sql
select pop as count, city as sum, loc as avg from zips
```
so that's cool.

**Comment by jdegoes** [comment]
Yes, definitely cool and something I've taken advantage of (both accidentally and intentionally).
