### ISSUE TITLE
admin: parse MongoDB URI from the clipboard

### ISSUE THREAD

**Issue by mossprescott** [slamdata/slamengine#557]
Add a button to the config dialog called "Paste MongoDB URI from Clipboard", so if you’ve copied the MongoDB URI from somewhere, you can paste it in.

**Comment by jdegoes** [comment]
Does this reverse-parse it and fill in all the fields so you can tweak them?

**Comment by mossprescott** [comment]
That’s the idea, yes. Working on it now.
