### ISSUE TITLE
admin: exporting data with Hebrew characters leads to CSV corruption

### ISSUE THREAD

**Issue by jdegoes** [slamdata/slamengine#568]
Commas need escaping in an Excel-compatible way. Should hopefully be an easy fix, would like to get it in very soon since this bug makes CSV export dramatically less useful.

*Update:* this is probably an encoding problem with unicode characters (Hebrew, in this case). See below.

**Comment by jdegoes** [comment]
I'll do a new release once this is in.

**Comment by mossprescott** [comment]
We're handling commas fine as far as I can tell. It would help to get an example query, source data, and/or csv output.

Here's a simple example, which seems to open fine in Numbers and in Google Drive/Sheets:
```
city,1
AGAWAM,"a, b, c"
CUSHMAN,"a, b, c"
BARRE,"a, b, c"
BELCHERTOWN,"a, b, c"
BLANDFORD,"a, b, c"
BRIMFIELD,"a, b, c"
CHESTER,"a, b, c"
CHICOPEE,"a, b, c"
CHICOPEE,"a, b, c"
WESTOVER AFB,"a, b, c"
CUMMINGTON,"a, b, c"
MOUNT TOM,"a, b, c"
EAST LONGMEADOW,"a, b, c"
```

**Comment by mossprescott** [comment]
Based on this screenshot and the email thread, it looks like we have at least a couple of problems:
- [ ] Probably not encoding the Hebrew characters right when writing the file.
- [ ] There's no indication of what format the export file will be in, and `.csv` is not supplied by default.

![4e8db33d-3138-4a43-aa93-8833521a36f1](https://cloud.githubusercontent.com/assets/6147371/5764320/4162b8a4-9cae-11e4-8021-90edc6975ad1.png)

**Comment by mossprescott** [comment]
All of the following work with some unicode strings I googled up and added to mongo:

- Running a simple query in the mongo shell, in our REPL, and in the admin UI.
- Both copying and exporting the result to CSV.

However, we are not specifying an encoding for writing the file, so Java is assuming the default encoding.  This is quite possibly different for me and Shy.

A possible workaround would be to start the JVM with `-Dfile.encoding=UTF-8`. If that helps, then probably the simplest fix is just to specify UTF-8 when writing the file.
