### ISSUE TITLE
Order of fields in result does not match SELECT

### ISSUE THREAD

**Issue by pjaffe** [slamdata/slamengine#584]
I assume these two behaviors are related, but maybe they should have been split into separate issue reports...

Using a simple Collection with this single document
    {  "_id" : "1",  "parentValue" : "Hi" }
The SlamSQL SELECT * FROM"/SimpleParent" returns just the parentValue. I understand from John De Goes that this is an artifact of how the _id field is handled, and that it needs to be explicitly called out in the SELECT.  I'm fine with that explanation.  So, if I do SELECT _id, * FROM"/SimpleParent" I get the _id field value and the parentValue field.

Now for the two behaviors that I would consider problems:

A). If I do SELECT p._id FROM "/SimpleParent" p, the result is a single record without any value.  I would have hoped this would have had the value of 1.  Although the Compiled plan includes the _id field in the $project and running it against my Mongo instance does return the single "1" value back.

B) And if I do SELECT p._id, parentValue FROM "/SimpleParent" p, the result is a single record that doesn't include the _id column.  Again, the Compiled plan includes the _id in the $project.

I understand that _id might be more succeptible to being ambiguous, but when fully qualified by a "table" alias, I would have hoped it would have been visible in the results.

**Comment by mossprescott** [comment]
In general, to get `_id` included in the result, you need to provide an alias to give the field a different name than `_id`. For example, either of these should work:
```sql
select _id as id from "/SimpleParent"
select _id as num, parentValue from "/SimpleParent"
```

The fact that `_id, *` works is actually more a bug than anything else, and as you found out, qualifying the field name with the table name doesn't help.

We understand that this behavior is sometimes confusing, and we're planning to address it in the future, by keeping track of whether `_id` is significant or not based on the query that generated each result collection.

**Comment by pjaffe** [comment]
Thanks for the quick reply on the weekend...

Now that I look back over my email exchange with John, he did specifically say " If you want the `_id` field, you can store it in a field manually".  So, the need to alias _id should have stuck in my head.

I did confirm that if I alias _id in my two example queries in this issue report, then I get the values back.  Although the order of the result columns for (B) appears to be inconsistent with the order specified in the SELECT.  I don't know whether you guys would consider that a bug, and whether that should be spun off as another defect.

I'll let you guys decide if you want to keep this defect open to track that, or feel free to close it if you are tracking that elsewhere.

**Comment by mossprescott** [comment]
Yes, we would consider incorrect order of columns a bug, and this is probably as good a place as any to track it. I'll update the description.

**Comment by jdegoes** [comment]
The case to investigate here is something like:

```sql
SELECT p._id AS id, parentValue FROM "/SimpleParent"
```

This should return JSON objects with the structure:

```json
{"id": "...", "parentValue": ".."}
```

and NOT the structure:

```json
{"parentValue": "..", "id": "..."}
```

**Comment by sellout** [comment]
I noticed the other day that we’re using `delegate` in `objectConcat`, and it doesn’t seem to do anything to handle the potential reversals. That seems like a good first suspect.

**Comment by mossprescott** [comment]
@sellout is correct, but there is also a more surprising cause.

If a final $project happens to include any fields which are projected directly from the source collection, *and not renamed*, then the order of those fields is not the order they are mentioned in the $project, but the order of the fields in the source. Any fields with "new" names always follow, in the order they appear. If all the fields are projected under different names, sanity resumes. Check this out:

```
💪 $ select a as a, b as b from "tmp.foo"
Query time: 0.0s
{ "b": 4, "a": 3 }
{ "a": 1, "b": 2 }

💪 $ select a as aa, b as bb from "tmp.foo"
Query time: 0.0s
{ "aa": 3, "bb": 4 }
{ "aa": 1, "bb": 2 }

💪 $ select 'x', a, b from "tmp.foo"
Query time: 0.0s
{ "a": 1, "b": 2, "0": "x" }
{ "b": 4, "a": 3, "0": "x" }
```

Yeah, that just happened.

I can think of several ways to fix this, but I don't like any of them all that much.

**Comment by jdegoes** [comment]
This seems like a bug in MongoDB, because they try to preserve field order, and have gotten better about this over time (insert/update used to ignore field order if the document had to be resized). 

Nonetheless, that's why they pay us (so to speak, anyway!), so we'll have to figure out a good solution for working around this -- ideally one which is robust to future fixes of this functionality in MongoDB.

**Comment by mossprescott** [comment]
After thinking about this for a bit, I think we could consider it another case where collection metadata comes to the rescue. Rather than building a more complex pipeline to get MongoDB to construct the data the right way, we could simply record the names of the fields with the results in the correct order (in the same way that if the results are projected under `value`, we would record that).

Then it would be up to the filesystem, when reading the collection, to put the fields in the right order as they're read.

That wouldn't help anyone running the plan outside of SlamEngine, or looking at the result collection using another tool, however.

**Comment by mossprescott** [comment]
I created another ticket (#598), to track the simpler case which seems like a MongoDB bug, and will use this ticket to track fixing the physical plan.
