### ISSUE TITLE
JOIN on _id versus non-_id field has different results

### ISSUE THREAD

**Issue by pjaffe** [slamdata/slamengine#585]
It's possible this is somehow related to core Mongo behavior that I don't understand, but it seems to me that this is the kind of stuff that the SlamSQL really is trying to abstract away, so I'm going to assume it is a SlamEngine "bug" for now.

Using two simple Collections:
```javascript
    SimpleParent: {  "_id" : "1",  "id": "1",  "parentValue" : "Hi" }
    SimpleChild: {  "_id": "11",  "parentId": "1",  "value": "Bye" }
```
The following SlamSQL results in the expected "Hi Bye" result
```SQL
    SELECT p.parentValue, c.value 
    FROM "/SimpleParent" p 
    LEFT OUTER JOIN "/SimpleChild" c ON c.parentId = p.id
```
However, the following SlamSQL joins on the parent's _id field versus its "duplicate" id field
```SQL
    SELECT p.parentValue, c.value 
    FROM "/SimpleParent" p 
    LEFT OUTER JOIN "/SimpleChild" c ON c.parentId = p._id
```
And this results in just "Hi" without the "Bye"

I compared the Compiled plan and both contain many references to the _id field, and the switch in the JOIN clause seems to only affect a single line in the return of a MapReduce apply.

But given that I gave the _id and id fields the exact same value, I would have expected the result to be the same.

Given that we have several Mongo collections whose documents reference each other by their _id value, this is a pretty important behavior for me to understand, and ideally see better supported in SlamEngine (unless I'm missing something here).

**Comment by mossprescott** [comment]
I suspect you're right and this is a bug in SlamEngine. We'll need to take a closer look to figure out what's going wrong, but I suspect the magic field `_id` is getting overwritten at some point.

**Comment by jdegoes** [comment]
Yes, this behavior is definitely a bug. You should get an empty set if `_id` and `parentId` have different types (e.g. OID versus String), and the non-empty one row result set with both "Hi" and "Bye" if they have the same type. 

In any case, we'll investigate and fix, thank you for reporting!

**Comment by sellout** [comment]
This looks like the same issue as #586, but with less disastrous results. IE, try reversing the condition for now, and I’ll get in a fix ASAP.

**Comment by pjaffe** [comment]
I confirmed that reversing the equality of the JOIN condition did fix the result.  Thanks for that tip.

I tried to find a formal specification of the join expression in ANSI SQL, but mostly just skimmed some examples, and they do seem to typically put the first table on the left side of the join expression.  But for some reason, I tend to think about it as reversed.  I assume you are agreeing that the order of that expression shouldn't influence the behavior, and I'm glad to hear you think it has a likely easy fix.  I could imagine other people stumbling into this.

**Comment by jdegoes** [comment]
The order should not influence behavior. INNER JOIN accepts an arbitrary boolean set (which represents a filter on the Cartesian cross product of the two sets being joined), so it shouldn't matter whether the table is on the left side or right side (or technically, any side at all!). We do have some limitations here, as we cannot accept arbitrary predicates, but this is definitely a bug and should have a straightforward fix.
