### ISSUE TITLE
SELECT of GROUP BY on a field within an array of subdocuments returns no results when arrays specified with [*]

### ISSUE THREAD

**Issue by pjaffe** [slamdata/slamengine#590]
Running admin_2.11-1.2.11-SNAPSHOT-one-jar.jar and using the data:
```
{"_id":"1","affiliations":[{"orgId":"1","orgRole":"Student","_id":"1"}]}
{"_id":"2","affiliations":[{"orgId":"2","orgRole":"Student","_id":"2"},{"orgId":"2","orgRole":"Instructor","_id":"3"}]}
{"_id":"3","affiliations":[{"orgId":"1","orgRole":"Student","_id":"4"}]}
```
I believe the following query:
```
SELECT DISTINCT affiliations[*].orgRole
  FROM "/Scratch" 
  GROUP BY affiliations[*].orgRole
```
should return the unique combination of orgRole values per Document. Hence I would expect the results:
orgRole.0 | orgRole.1
------------ | ------------
Student |
Student | Instructor

However, it generates no results.

*Note that removing the "[***]" from the SELECT clause currently does return results, but that is understood to not be the right approach, and is expected to be blocked once #589 is addressed.*

**Comment by sellout** [comment]
There is definitely a bug in this query, but the correct compiler output should should look like
```javascript
db.Scratch.aggregate([
    { "$unwind" : "$affiliations"},
    { "$project" : { "orgRole" : "$affiliations.orgRole"}},
    { "$group" : { "__tmp0" : { "$first" : "$$ROOT"} , "_id" : { "0" : "$orgRole"}}},
    { "$project" : { "orgRole" : "$__tmp0.orgRole" , "_id" : false}},
    { "$out" : "tmp.gen_0"}
  ],
  { allowDiskUse: true })
db.tmp.gen_0.find()
```
with the results:
```
orgRole
------------
Student
Instructor
```

**Comment by pjaffe** [comment]
Sounds like you agree that there is a SlamData bug here, but if I'm interpreting your reply correctly, my originaly assumption regarding the expected output was wrong.

Is there a SlamSQL that would generate the results I originally expected? ... where the grouping is on the various "array of values" versus treating each value individually?

**Comment by jdegoes** [comment]
What sort of semantics do you want when grouping on the array of values? I assume set semantics would be the most useful, i.e. group on composite combinations of different roles.

**Comment by pjaffe** [comment]
It's one of those cases where ideally I'd have various options.  I could imagine 3 options:
1. Values from within the array are all treated as equals, regardless of their containment in parent documents (and hence relationship to siblings)
2. An array within a parent document is treated as a set, and is grouped/compared against other sets of siblings of its parent, and where order is significant, so a "value1, value2" is distinct from "value2, value1"... as would be a "value1,value1" from "value1"
3. Similar to the previous, but with the option to make them order independent. So "value1,value2" are considered the same as "value2,value1".
4. Similar to the previous where arrays can be reduced to their distinct values, so "value1" is the same as "value1,value1".

Although, things might get even more complicated when considering multiple levels of depth.  I haven't given that much thought yet.

In the end, I mostly just want to understand the semantics of what is currently supported, and then see what other options might naturally fall out of that.

**Comment by jdegoes** [comment]
Currently, you can group by arrays, but the group keys will be considered distinct if they differ in length or in content for any element; i.e. true array semantics.

**Comment by pjaffe** [comment]
I ran the latest version of the admin jar (Admin v1.2.11-SNAPSHOT-869, sha 4a9b703), and confirmed that I now do get results from this query.  However, can you clarify whether I correctly noted a potential contradiction between jdegoes and sellout's comments above?

jdegoes' said:
> you can group by arrays, but the group keys will be considered distinct if they differ in length or in content for any element; i.e. true array semantics

which made me think the result would contain unique arrays, such as the following (given my sample data above):

orgRole.0 | orgRole.1
------------ | ------------
Student | 
Student | Instructor

But, with the related fix to #594, I see the following behavior in SlamData, which is what sellout seemed to imply, hence my question about the potential contradiction:

orgRole | 
---------- | 
Student | 
Instructor | 

1. Is there a different form of GROUP BY expression that can flip between the two forms of results?  
2. Or is the second one really the only designed behavior?  
3. Maybe the former only comes out of doing GROUP BY on arrays without the "[***]" designator, which I understand is a non-supported mode per #589?

**Comment by jdegoes** [comment]
Hi Peter, which query are you using to produce the above result? When you group by `orgRole[*]`, you are flattening out all the array elements, but when you group by `orgRole`, you are grouping by the entire contents of the array. Does that make sense?

**Comment by sellout** [comment]
If you were to group by `affiliations` it would compare against the entire array (which I think is what @jdegoes meant), EG: `[{"orgId":"2","orgRole":"Student","_id":"2"},{"orgId":"2","orgRole":"Instructor","_id":"3"}]`.

Grouping by `affiliations[*]` splits the array into separate records, duplicating the other fields, so you’d be comparing `{"orgId":"2","orgRole":"Student","_id":"2"}`.

Finally, grouping by `affiliations[*].orgRole` does the array splitting, then projects orgRole from the object, performing the comparison on `"Student"`. This is why you get the result I mentioned.

I don’t think it’s currently possible to get exactly what you want – which is to map across the array, pulling out the `orgRole` from each object (IE, not doing the array splitting), and comparing on `["Student", "Instructor"]`.

This is something we plan to support down the road, though.

**Comment by jdegoes** [comment]
@sellout This would be `[affiliations[**].orgRole ...]` under MRA, i.e. pull out the array dimension, project `orgRole`, and build up the array again (reducing the new array dimension).

**Comment by pjaffe** [comment]
@sellout Thanks for the clarification on behavior.  I was able to demonstrate to myself:
* `GROUP BY affiliations` grouping on exact equality of complete arrays across documents
* `GROUP BY affiliations[*]` grouping on exact equality of the individual subdocuments across arrays
* `GROUP BY affiliations[*].orgRole` grouping on the individual field value across all subdocuments in all arrays.

I feel like these are important behaviors to have documented somewhere.

I also believe it will be helpful for my client to be able to group on a projection of a field within an array, as @jdegoes suggested in his previous comment.  And this would generate a result set like:

orgRole.0 | orgRole.1
------------ | -------------
Student | 
Student | Instructor

that I hypothesized above. Is there an issue to track that, or is that more of a roadmap concept that maybe you aren't tracking as discrete enhancement issues yet?  

I could also imagine the desire to group on two or more fields within an array of subdocuments.  Using the sample JSON included in this issue, it would be grouping on `orgRole` and `orgId`, thereby avoiding grouping on the globally unique `_id` value that each of our subdocuments in the array contain (e.g. `GROUP BY affiliations[*]` won't ever find a match because of the contained _id field).  

I just experimented with `GROUP BY affiliations.orgRole`, and it appears to potentially accomplish this.  As does `GROUP BY affiliations.orgRole, affiliations.orgId` for grouping on each array's representation of a combinations of a subset of its fields.  But, maybe @jdegoes's previous comment and also #589 imply I shouldn't trust these, and instead they should instead eventually be:
* `GROUP BY affiliations[**].orgRole`
* `GROUP BY affiliations[**].orgRole, affiliations[**].orgId`

since that would provide SlamData an explicit indicator that the field should be treated as an Array.

So far I have assumed syntax like `[*]` is specific to SlamSQL, and @jdegoes's use of the term "MRA" is just a general reference to SlamSQL converting to "MapReduce/Aggregation" Mongo statements. But I wonder if I'm missing some more general concept beyond SlamData here.  I have also wondered whether the `{*}` projection syntax referenced on the SlamData Documentation page is intended to behave identically to `[*]`, or if it is different in some way?

**Comment by jdegoes** [comment]
@pjaffe There are various tickets related to MRA, but not one specifically for this feature. As soon as I wrap up some of the front-end spec work I'm doing for SD 2.0, I'll move on to creating a family of tickets that will track these and other important issues. MRA stands for "multi-dimensional relational algebra", and it's the foundation of SlamSQL, which allows doing general-purpose analytics with nested, non-uniform data. We currently do not support 100% of MRA (but it's a big priority after 1.3).

If you want to group on two values of subdocuments in an array, you can do that today:

```SQL
GROUP BY affiliations[*].orgRole, affiliations[*].orgId
```

If you're looking for cliff notes on the projection operators:

* `.foo`. Projects out the specified field from the object. Equivalent to `{"foo"}`. One-to-one.
* `[n]`. Projects out the specified element from the array. One-to-one.
* `{*}`. Projects out **all** the fields from the object. One-to-many.
* `[*]`. Projects out **all** the elements from the array. One-to-many.

MRA functionality we do not yet support:

* `[foo ...]`. Reduces the set `foo` into an array. Many-to-one. This is similar to `ARRAY_AGG` in Postgres and we will have such a synonym for the syntax.
* `{foo : bar ...}`. Reduces the sets `foo` and `bar` into an object with field names `foo` and values `bar`. Many-to-one.
* `[**]`. Think of this as loosely equivalent to grouping the elements of the array by "array identity". Such that if you `COUNT(myarray[**]), you get the length of the array. Keep in mind that MRA supports "nested grouping", so you can group things 2 times and rollup 2 times. One-to-many.
* `{**}`. Think of this as loosely equivalent to grouping the values of the object by "object identity". Such that if you `COUNT(myobj[**])`, you get the number of fields in the object. One-to-many.

I will be writing all this up for public consumption -- right after spec work for SD 2.0 and MRA. :smile: So hopefully late this month.
