### ISSUE TITLE
Error when ORDER BY references raw field name when SELECT aliases the field, and field is in GROUP BY and additional fields are returned in the SELECT results

### ISSUE THREAD

**Issue by pjaffe** [slamdata/slamengine#597]
This had worked against the admin jar released under SHA d9c9ac0 (SNAPHSHOT 861) and fails under SHA 4a9b703 (SNAPHSHOT 869).  There is an easy workaround of changing the ORDER BY clause to reference the field Alias name, versus the raw field name.  However, I believe ANSI SQL allows for referencing the actual field names in the ORDER BY, and this appears to be a regression issue.
```
SELECT distinct category AS "Result Alias", COUNT(*)
	FROM "/SimpleParent"
	GROUP BY category
	ORDER BY category
```
Fails with:
```
java.lang.RuntimeException: cannot merge class slamdata.engine.physical.mongodb.Workflow$$Read with class slamdata.engine.physical.mongodb.Workflow$$Group
```
But any of the following mitigate the error (the first two at least still provide access to the same result data):
* Changing the ORDER BY to be ORDER BY "Result Alias"
* Removing the AS "Result Alias" from the SELECT
* Removing the ORDER BY clause
* Removing the GROUP BY clause
* Removing the COUNT(*) from the SELECT results

**Comment by jdegoes** [comment]
@pjaffe Thanks for reporting, we'll take a look!

@sellout / @mossprescott Be sure to get at least one regression test in here for this bug.

**Comment by sellout** [comment]
Removing `distinct` also removes the error, and gives a similar result (just with duplicates).

It seems the problem in somewhere in `arrayConcat`ing the key fields for `distinct` – which is frustrating, because we throw away the arrays (`CollectionBuilder`s) generated for sort/group/distinct/etc. keys. And, since we throw them away, we haven’t given them much care – anything involving arrays falls immediately down to `Workflow`, and thus crystalizes the builder history. In this case, we wind up with two `Workflow`s that won’t merge.

**Comment by sellout** [comment]
Translating to our test data again …
```sql
SELECT distinct sha AS "Result Alias", COUNT(*)
    FROM "/SimpleParent"
    GROUP BY sha
    ORDER BY sha
```

**Comment by sellout** [comment]
Ok, yeah, I just disabled `arrayConcat` and this query works just fine. Argh! Something something non-strict semantics.

Anyway, while it would be nice to punt on this stuff until we actually need it (I don’t think our stdlib has any way to create or concat an array yet – is there any other place that does this?), we should probably come up with something. I’m thinking an `ArrayBuilder` for now, containing a list of `ExprOp \/ JsMacro`.

Comments?

**Comment by jdegoes** [comment]
No punting unless the work we do now will be throwaway because of some larger changes, e.g. MRA (which it doesn't seem like will be the case???).

The standard library has make array and array concat. Or at least, did at one point. Gone now?

**Comment by sellout** [comment]
Yeah, we can’t really punt – and you’re right, those functions are there, just under “structural”, not “array”, so I missed them. And, of course they have to exist, since we use them in the logical plan – I just spaced.
