### ISSUE TITLE
mongodb: `id`s don’t match on GroupBuilders when they should

### ISSUE THREAD

**Issue by sellout** [slamdata/slamengine#603]
@ioRekz reported slamdata/slamdata#197, which is really an engine issue.

The query
```sql
select sum(win), sum(loose) from "/events" where event='clutch'
```
fails with a “can not objectConcat” error, because two concatable GroupBuilders end up with different `id`s.

This is a regression since version 1.2(?) – almost certainly a result of the new GroupBuilder.

**Comment by jdegoes** [comment]
We need a lot more regression tests too guard against these 'combination' cases.

**Comment by mossprescott** [comment]
Yup, we were missing this case (filter, no explicit group by) from the property-based tests for planner. I'll be sure to add that, and probably some more, so we don't get surprised again.

**Comment by mossprescott** [comment]
A quick workaround is to add `group by null` to the query.

**Comment by jdegoes** [comment]
:+1: to "no surprises again", especially for simple queries like this one. :smile:
