### ISSUE TITLE
logical plan: bad plan with constant projection

### ISSUE THREAD

**Issue by sellout** [slamdata/slamengine#608]
As @mossprescott pointed out earlier, we do the wrong thing with
```sql
select 1 from zips
```
This should result in `select count(*) frrom zips` records, each with a single field containing `1`, but it generates a single record and is identical to
```sql
select 1
```

Here is the generated plan:
```
Logical Plan
Let('tmp0)
├─ Read(./zips)
╰─ Let('tmp1)
   ├─ OneToOne(MAKE_OBJECT)
   │  ├─ Constant(Str(0))
   │  ╰─ Constant(Int(1))
   ╰─ Let('tmp2)
      ├─ Squashing(SQUASH)
      │  ╰─ Free('tmp1)
      ╰─ Free('tmp2)

Simplified
Squashing(SQUASH)
╰─ OneToOne(MAKE_OBJECT)
   ├─ Constant(Str(0))
   ╰─ Constant(Int(1))
```
   
You can see that the simplified plan has no reference to the collection, and that makes sense given that the original plan never refers to it.

**Comment by jdegoes** [comment]
We need a new std function to compile this query (and other queries which only coincidentally work right now).

At the logical plan level, we need something like:

```
with_value(read("/zips"), 1)
```

Where the left set is auto-joined to the right set, and the value on the right side is used.

**Comment by jdegoes** [comment]
The query `count(1)` works coincidentally, as this should actually return 1 under MRA, but not under SQL. The same sort of `with_value` / `set_value` function is needed to compile aggregations of constants down to the correct logical plan.
