### ISSUE TITLE
plannr: issue when grouping by array element

### ISSUE THREAD

**Issue by jdegoes** [slamdata/slamengine#620]
See [here](https://slamdata.supportbee.com/tickets/4527614) for context.

### Original Query w/Incorrect Results

```sql
SELECT DISTINCT events[0].type, COUNT(events[0].type) AS count
FROM “/test/usage”
GROUP BY events[0].type
```

------------------------------

```
2235       headUnitConnect

2235       headUnitDisconnect

2235       appEvent
```

### Alternate Queries w/Correct Results

```sql
SELECT COUNT(events[0].type) AS count
FROM "/preprod/app_usg"
WHERE events[0].type = 'appEvent'
```

```sql
SELECT COUNT(events[0].type) AS count
FROM "/preprod/app_usg"
WHERE events[0].type = 'headunitDisconnect'
``` 

```sql
SELECT COUNT(events[0].type) AS count
FROM "/preprod/app_usg"
WHERE events[0].type = 'headUnitConnect"
```

------------------------------

```
200       appEvent
1350      headUnitDisconnect
685       headUnitConnect
```

**Comment by jdegoes** [comment]
A second issue is that replacing the above `COUNT` in the original query with `COUNT(*)` yields an error.

**Comment by sellout** [comment]
The one with incorrect results (and the `COUNT(*)` version of it) gives me a SQL parser error, but I don’t see anything wrong with it.

The others work fine.

**Comment by jdegoes** [comment]
Work fine, i.e. give correct count results?

**Comment by jdegoes** [comment]
I was assuming this issue was caused by interplay between Map/Reduce and grouping (since the `[0]` will trigger a MR).

**Comment by jdegoes** [comment]
Would be nice if it was "just" a SQL parsing error.

**Comment by sellout** [comment]
“Work fine” as in “generates a physical plan”. I don’t have the collection in question to check the counts.

But … it turns out the problem was your version had some Unicode quotes swapped in. I can now get it to generate a plan.

**Comment by jdegoes** [comment]
Ah, OK. I doubt the customer was using the unicode quotes, they probably appeared in the text client -- but if the plan ends up looking correct, happy to go back and suggest re-running it with ordinary quotes. Speaking of which, we may want to enforce that in the Admin GUI.

**Comment by sellout** [comment]
Oh, no – I discovered the problem by copying the version from SupportBee, which had ordinary quotes. Definitely not what the customer was running into.

**Comment by sellout** [comment]
Got this one sorted. It was bad handling of `projectIndex` on a group (which is basically what you assumed, except that it happens before it actually becomes a MapReduce). The `COUNT(*)` error was really just a consequence of the non-sensical builder created by the first issue.

PR coming ASAP.

**Comment by sellout** [comment]
Also, those successful cases create pretty bad queries (`mapReduce; aggregate; mapReduce; aggregate`) because of a similar issue with `projectIndex` and `ShapePreservingBuilder`. So I’m fixing that as well, so they’ll look like `mapReduce; aggregate`.

**Comment by jdegoes** [comment]
Let's get some unit and regression tests for these types of queries into the PR (I was quite surprised it didn't work since it's pretty basic sort of query -- just the combination of a bunch of edge cases, I guess).

**Comment by jdegoes** [comment]
I'll cut a new release after you get this in, BTW, and update the user appropriately.

**Comment by sellout** [comment]
This is again a case where I feel like MRA will help, because we’ll see where the dimensionality doesn’t line up.

**Comment by jdegoes** [comment]
:cry: Well let's get through 1.3, then MRA is on the table...
