### ISSUE TITLE
admin: loading message appears forever in collection with 500 records

### ISSUE THREAD

**Issue by jdegoes** [slamdata/slamengine#624]
See [here](https://slamdata.supportbee.com/tickets/3878583) for context.

It looks like the table component may not be capable of displaying certain kinds of data (maybe it crashes, because it displays the Loading message forever). Or it could be an issue with the API.

The sample data suggests this could be connected to binary data, or arrays of binary data, which are probably not all that well tested.

**Comment by mossprescott** [comment]
The table has no trouble with simple un-nested binary data, but I was able to reproduce the problem with a single record taken from the supportbee ticket. It's probably something simple. I should have a fix shortly.

**Comment by jdegoes** [comment]
OK, this is important enough I'll cut a new release once we get your fix merged in.

**Comment by mossprescott** [comment]
We aren't decoding binary type 3 ("UUID (old)"), which comes back as a `java.util.UUID`. And when decoding fails, we're not handling it very gracefully.
