### ISSUE TITLE
SQL: implement EXTRACT(field FROM value) syntax

### ISSUE THREAD

**Issue by mossprescott** [slamdata/slamengine#629]
This is apparently the SQL standard way of pulling fields out of date/time values. Note that `field` is "an identifier or string", which may be one of "minute", "hour", etc. 

We support the alternative `date_part(fieldStr, value)` syntax, which fits much more nicely into everything else we do and doesn't require any special syntax.

Note: prior to #430, we could parse the EXTRACT syntax, at least in some cases, but did not implement it in the compiler.

**Comment by jdegoes** [comment]
I think we have a ticket for this somewhere...

**Comment by mossprescott** [comment]
Dupe for #210. Thanks @jdegoes!
