### ISSUE TITLE
compiler: error with join and order by

### ISSUE THREAD

**Issue by mossprescott** [slamdata/slamengine#640]
The "synthetic" projection that we introduce for sorting is invalid in the presence of a join. For example, the following query:
```sql
select * from a left join b on a.id = b.id order by a.rank
```
Produces this error: `No table was defined in the scope of '__sd__0'`

**Comment by sellout** [comment]
ARGH! Long update killed by broken waffle.io! Lucky, you now get the short version:

```sql
select *, a.rank as meh from a left join b on a.id = b.id order by meh
```
has the same behavior. Basically, `order by` should see aliases but doesn’t. Coincidentally works on a single table, as we just assume the field exists on the table, and then it resolves to the alias later down the road.

So … I think we need to have the named projections in scope for calls to `compile0(Ident)` within `order by`.
