### ISSUE TITLE
api: use `Accept` header to decide between strict / non-strict JSON mode

### ISSUE THREAD

**Issue by jdegoes** [slamdata/slamengine#644]

**Comment by sellout** [comment]
Does Unfiltered give us anything to help with the somewhat-complicated Accept header rules, or do we just get a list of values and need to sort it all out?

What should the syntax be? `application/json;mode=precise` (and `readable`)?

And I assume we prefer `precise` if the client doesn’t specify (or gives them the same priority).

**Comment by jdegoes** [comment]
The default should be readable simply because 'precise' is our own DSL embedded into JSON. Technically what we are returning is not json but line delimited json. There are sort-of agreed upon mime types and file extensions for this format, see [here](http://en.wikipedia.org/wiki/Line_Delimited_JSON), we should probably be generous as possible because it's early in standardization (e.g. accept both application/ldjson and application/x-ldjson).

Likely Unfiltered will give you a list of values and require you sort it out, probably same with http4s but check in to make sure.

**Comment by jdegoes** [comment]
Oh, and `application/json; boundary=NL`.

**Comment by sellout** [comment]
Looks like http4s has nice Accept processing. But I guess this should wait on #675.

**Comment by mossprescott** [comment]
You could probably say the same about most of the api tickets. I got a start on #675 yesterday, and should get further on Tuesday/Wednesday. 

Related question: do you want to take a look at Project ρ? It may make all of the path/query handling a lot easier, but I haven't looked into it enough to know if it's ready for prime time.
