### ISSUE TITLE
can't use epoch value. throwing numberformat error

### ISSUE THREAD

**Issue by mayurmahajan** [slamdata/slamengine#649]
Following query gave me error :-
select * from users where add_date > 1425460451000;
error message :- java.lang.NumberFormatException: For input string: "1425460451000"

1425460451000 is an epoch value, how can I make use of it in my query?

**Comment by sellout** [comment]
Whoops – there is a bug where we try to parse a `long` value as an `int`. I’ll get this fix in ASAP.

**Comment by sellout** [comment]
@mayurmahajan – you can download [a new build with this fix](https://github.com/slamdata/slamengine/releases/tag/v1.3.1-SNAPSHOT-1010-admin), if you’re not using the git repo directly.

**Comment by jdegoes** [comment]
Hi @mayurmahajan, I have released SlamData 1.3.1 which fixes this functionality, and you can [download the new installers from the SlamData website](http://slamdata.com).

**Comment by mayurmahajan** [comment]
I installed the latest version, the issue is gone. Thank you!

**Comment by jdegoes** [comment]
You're welcome, thanks for reporting!
