### ISSUE TITLE
mongo: use java driver 3.0

### ISSUE THREAD

**Issue by jdegoes** [slamdata/slamengine#658]
https://github.com/mongodb/mongo-java-driver/releases

**Comment by sellout** [comment]
Is this really a bug? I know it would be nice to use the new driver, but do we have any current issues that would be mitigated by the switch?

**Comment by jdegoes** [comment]
Yes, it's SlamData is currently incompatible with WiredTiger, or at least important bits of functionality won't work without this upgrade.
