### ISSUE TITLE
ODBC?

### ISSUE THREAD

**Issue by chrislarsenqlik** [slamdata/slamengine#660]
Hi, I have used the tool and think it's great, I like how many features you support. 

What I'm coming up short on is ODBC connectivity, which is necessary to drive adoption of BI or ETL tools.. otherwise Mongo is on an island. Seems like it would be easy to have Simba or some other driver pass the sql query across to your engine and return the results. Is this on the roadmap? Is it possible today?

**Comment by jdegoes** [comment]
Hi Chris!

Simba sells an ODBC driver for MongoDB, as do Progress Software and UnityJDBC. In addition, several open source projects offer one through a roundabout means (e.g. [Apache Drill](http://drill.apache.org/blog/2014/11/19/sql-on-mongodb/), which has ODBC / JDBC drivers, and [EnterpriseDB](https://github.com/EnterpriseDB/mongo_fdw), which also has drivers).

We do have an early stage driver in a closed repository, but given the wealth of options available here, it's not our primary focus. We're more focused on enabling users to use SlamData to build the early stage of their analytic pipelines directly (data exploration, data refinement, aggregation, etc., possibly before exporting aggregated, clean data into another tool further downstream).

NoSQL data is often messy and nested, sometimes with lots of free text, and BI tools don't really know what to do with it, even in the presence of an ODBC driver. 

That said, we're an open source project, so we accept third-party pull requests and also do sponsored open source development (even for things not on our roadmap), so if you run into a company for whom this is a priority, just put them in touch with us. We have 100% pushdown technology which we consider best-in-class for this type of problem.
