### ISSUE TITLE
admin: allow different databases for auth and data

### ISSUE THREAD

**Issue by oz123** [slamdata/slamengine#662]
My users and passwords are stored in the database admin, so I can connect with slamdata to my admin db. With:
 
       mongodb://$user:$pass@host:port/admin

But I would to connent to the database `foo`:

        mongodb://$user:$pass@host:port/foo

The same thing with foo works with Robomongo GUI. 

At the same note, how do you access the web UI on mac os? I tried accessing the port given in "Edit SlamData Configuration". But without success.

**Comment by mossprescott** [comment]
The configuration UI assumes that the database you use to connect is the same as the one you want to run queries against, but in fact it's possible to configure SlamEngine with separate databases. You'll need to manually edit the config file, which is found in your home directory (on MacOS, it's under `Library/Application Support/slamdata/slamengine-config.json`).

You want to change the mountings section to look something like this:
```JSON
    "/": {
      "mongodb": {
        "database": "foo",
        "connectionUri": "mongodb://user:pass@host:port/admin"
      }
    },
```

To access the web API (for programs to talk to), you need to run the separate JAR available here: https://github.com/slamdata/slamengine/releases. The port you can configure is the port for the web API.

The web front-end (for humans and web browsers) is not available for the latest versions of SlamData, but will be relaunching for 2.0.

**Comment by jdegoes** [comment]
We should also test that you can enter ssh key connectionURI without the parser dropping anything... there's a ticket over on SupportBees about this where you can grab a test URI.

**Comment by jdegoes** [comment]
Closing in favor of #674. However, we should still verify SSH keys work in the admin interface.
