### ISSUE TITLE
std/mongodb: support string expressions for OID function

### ISSUE THREAD

**Issue by jdegoes** [slamdata/slamengine#672]
The OID unary operator should work not only with String literals, but also with string expressions. This is necessary because sometimes users store a foreign document ID as a string inside a document, which means they need to convert this into an OID when doing joins.

**Comment by jdegoes** [comment]
MongoDB does not have a way to do this outside of MapReduce (AFAICT), but this functionality would be used primarily during joins which require MR anyway.

**Comment by sellout** [comment]
Joins require MR only for the _right_ side, but #588 can help here – it would let us swap left/right if only the left side needs a MR.

EG, `a join b on oid(a.id) = b.id` is probably a lot slower than `b join a on b.id = oid(a.id)` with the current impl, but no reason it should stay that way.
