### ISSUE TITLE
mongodb: completely change how mounting works for mongodb

### ISSUE THREAD

**Issue by jdegoes** [slamdata/slamengine#674]
Currently, we require users specify the authentication database on the Connection URI, and the database to mount at the specified path separately.

To simplify administration and avoid implementing features that would have to be present in any authorization scheme, we're going to change this completely.

Instead, the user will specify the authentication database in the Connection URI, and *all databases the user has access to will be mounted as children of the mount path*.

SD 2.0 will be assuming this scheme which is why this is targeted ASAP for 1.4. It deprecates #662.

**Comment by jdegoes** [comment]
This will involve a change / simplification to the Admin GUI, as well.

**Comment by jdegoes** [comment]
This is how we'd do RDBMS mounts, too: mount the database, and you get all tables under the mounted path. Etc.

**Comment by mossprescott** [comment]
@jdegoes: after getting this mostly working, a couple of edge cases have come up:

1) When generating temporary collections, we need to decide which database to put them in. If a query contains *any* reads, or if there is an output collection specified, we can (indeed *must*) use that. But in the pathological case of a query referencing no sources and with no output collection specified, we need to choose a database for the result, or else fail. I don't think it matters much what we choose.

2) The user may not have permission to list the available databases. on mongolabs, I'm getting this error: `not authorized on admin to execute command { listDatabases: 1 }' on server ds045089.mongolab.com:45089`. In that case, we need some way for the user to specify the database(s) in configuration. I don't know how common this is going to be for users—it may be a mongolabs quirk. 

I think we can work around both of these (at least for now) by just attempting to list the databases, and if it fails falling back to using the single database name that must be included in the connectionUri. We can also use that database as the "default" for the trivial queries in case (1). How does that sound?

**Comment by jdegoes** [comment]
1. I think that's correct. If you wanted to make the code smart about it, you could write to the first database with write permissions for the user, or at least, try them serially until one succeeds.
2. Interesting. Security by obscurity, I guess. I would suggest we use the authentication database for now. We can always add a "slamdata.db" property to the Connection URI, which we wouldn't send along to mongodb, but which we would use for purposes of determining which database to connect to.
