### ISSUE TITLE
Can no longer connect to web API

### ISSUE THREAD

**Issue by puffnfresh** [slamdata/slamengine#689]
Since the http4s change, it looks like the web API is binding on `127.0.0.1:8000` instead of `0.0.0.0:8000`. This is preventing me from connecting to the engine.

**Comment by puffnfresh** [comment]
The `Access-Control-Allow-Origin` header is now missing, too.

**Comment by mossprescott** [comment]
Looks like you found two missing tests for the API.

The Access-Control-Allow-Origin header should be handled by the CORS middleware which is coming in http4s 0.7, but we could probably roll our own middleware just for that in the meantime. Would you like me to look into it?

**Comment by puffnfresh** [comment]
@mossprescott I added the missing CORS response to all of the services in #690. I saw the middleware in http4s master, that will clean things up.

**Comment by puffnfresh** [comment]
Seems like I still can't connect. I've added the CORS headers and we're now listening on all interfaces but I'm still getting CROS errors from the UI.

**Comment by puffnfresh** [comment]
The specific error Chrome is giving:

> No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by jdegoes** [comment]
Do a dump of the response headers during OPTIONS specifically, and GET / PUT / POST or whatever actual API is being invoked.

**Comment by jdegoes** [comment]
Chrome's debug tools should let you peer into the response headers to see what the server is actually returning.

**Comment by puffnfresh** [comment]
Chrome is not preflighting the request (i.e. doing the additional OPTIONS request) since it's just a simple GET without any custom headers. Two options:

1. Add a custom header to the requests on the UI side.
2. Make all responses have the CORS headers.

I'm working on option 2.

**Comment by jdegoes** [comment]
Yes, (2) sounds ideal.
