### ISSUE TITLE
Move/Rename

### ISSUE THREAD

**Issue by cryogenian** [slamdata/slamengine#693]
* When I try to move file to its own location (i.e. `bar/foo.json` -> `bar/foo.json`) it disappears with error 
```json
{ 
"serverUsed" : "localhost:27017" , 
"ok" : 0.0 , "errmsg" : 
"BadValue from namespace doesn't exist"
}
```
I remember that I had similar bug when I had tried to move directory to file path. (`/bar/foo/` -> `/bar/baz`) but can't reproduce it 
* When I move file to destination where other file exists, second file silently removed. Is it possible to add server-side check or additional parameter?

**Comment by jdegoes** [comment]
Definitely a serious bug in need of fixing. :)

**Comment by jdegoes** [comment]
Move of a file to itself should succeed with no effect, while move of one file to another should fail with error message.
