### ISSUE TITLE
get jenkins server building, deploying slamengine + slamdata

### ISSUE THREAD

**Issue by jdegoes** [slamdata/slamengine#709]
We're going to deploy this as a live demo on the slamdata website, it can also be used for interactive testing of HEAD of the respective repositories. the installers scripts may or may not be useful. talk to @cryogenian for details on launching the frontend.

**Comment by mossprescott** [comment]
I've made some progress on this, building SlamEngine and SlamData separately and then assembling the products in another Jenkins project. The idea is just to start the API server the same way we were formerly running the API server alone on the Jenkins server, but with the front-end's static files available.

@sellout: For the time being, I'm building your ready/482 branch, and I'm running into a problem with the way it locates the static files. Apparently, the CodeSource you're using to find the path is null (at least, I'm guessing that's what's null, in any case it's something in that line of code). How would you feel about adding a parameter to specify the path explicitly?

**Comment by mossprescott** [comment]
Correction, it looks like `getPath` on the URI form of the code source's location is what's null.

**Comment by mossprescott** [comment]
Ugh, here's the URI: `jar:file:/var/lib/jenkins/workspace/SlamEngine-Start-API-Server/web_2.11-2.0.0-SNAPSHOT-one-jar.jar!/main/web_2.11-2.0.0-SNAPSHOT.jar`.

So I could parse the `file:` part out of that, but, yeah.

**Comment by sellout** [comment]
Sorry, that's what I was working on when I went home at lunch, and have been to sick to do anything 😕

I think adding a parameter for the path sounds good. Also useful for running from sbt without having to symlink the web content in the right place.

**Comment by mossprescott** [comment]
Should be good to go, but needs a merge on the other repository to build without manual intervention (slamdata/slamdata#98). Will close once that's in place and the build seems stable.

**Comment by jdegoes** [comment]
@mossprescott slamdata/slamdata#98 was merged, so back to you.

**Comment by mossprescott** [comment]
Looks good after clean builds of both repositories. Also, the filesystem UI seems to be working better now.
