### ISSUE TITLE
API: cannot move a directory

### ISSUE THREAD

**Issue by cryogenian** [slamdata/slamengine#711]
```
> use foo
switched to db foo
> show collections
Untitled\.slam.index
aabbc
bar.bazqqdasf
baz.quux
system.indexes
``` 
http://local.slamdata.com/metadata/fs//foo/foo/
```json
{
    "children": [
        {
            "name": "Untitled.slam",
            "type": "directory"
        },
        {
            "name": "aabbc",
            "type": "file"
        },
        {
            "name": "bar",
            "type": "directory"
        },
        {
            "name": "baz",
            "type": "directory"
        },
        {
            "name": "system",
            "type": "directory"
        }
    ]
}
```
MOVE@http://local.slamdata.com/data/fs//foo/foo/Untitled.slam/
DESTINATION: /foo/foo/U.slam/
ERROR: No file/dir at path: ./foo/Untitled.slam

**Comment by mossprescott** [comment]
Looks like the trailing slash is getting swallowed by http4s, which was a known issue but wasn't biting us until you tried this.

It looks like http4s 0.7 is out, which should have the fix I submitted for this. I'll update the dependency and see if I can get a unit test in for the API, too.

**Comment by jdegoes** [comment]
> if I can get a unit test in for the API, too.

:+1:

**Comment by mossprescott** [comment]
Per discussion on #710, should also allow a non-existent directory to be moved to another non-existent location (since MongoDB treats empty directories as non-existent).
