### ISSUE TITLE
duplicated result in post

### ISSUE THREAD

**Issue by cryogenian** [slamdata/slamengine#721]
```sql
select * from "/foo/foo/aabbc" where (
  "userId" LIKE '%female%' OR 
  "userId" = 'female' OR 
  "profile"."name" LIKE '%female%' OR 
  "profile"."name" = 'female' OR 
  "profile"."age" LIKE '%female%' OR 
  "profile"."age" = 'female' OR 
  "profile"."gender" LIKE '%female%' OR 
  "profile"."gender" = 'female' OR 
  "comments"[*]."id" LIKE '%female%' OR 
  "comments"[*]."id" = 'female' OR 
  "comments"[*]."text" LIKE '%female%' OR 
  "comments"[*]."text" = 'female' OR 
  "comments"[*]."replyTo"[*] LIKE '%female%' OR 
  "comments"[*]."replyTo"[*] = 'female' OR 
  "comments"[*]."time" LIKE '%female%' OR "comments"[*]."time" = 'female')
```
produces 128 identical results 
```sql 
select * from "/foo/foo/aabbc" where (
  profile.gender LIKE '%female%' OR 
  profile.gender = 'female')
```
produces 1 result

**Comment by jdegoes** [comment]
There should be *some* duplicates in this, because we don't actually support the MRA query that would perform no duplication, e.g.:

```sql
SELECT * FROM "/foo" WHERE EXISTS(comments[_].id LIKE '%female%')
```

Nonetheless, the number of duplicates seems to high -- it should be equal to the size of the first array multiplied by the size of the second array (how big are they?).

My guess is we're doing duplicate unwinds on the 2nd array flattening of `replyTo`, since I know @sellout  already fixed duplication of first-order unwinds.

**Comment by jdegoes** [comment]
By the way, for now, until we support more of MRA, I'd change your `SELECT` into a `SELECT DISTINCT`.

**Comment by sellout** [comment]
Isn’t `where (profile.gender LIKE '%female%' OR profile.gender = 'female')` identical to `where profile.gender LIKE '%female%'`? Not that it’s a big deal – just seems like something that could be simplified (and eventually the compiler should be able to reduce it, but currently it can’t).

And is there a data file for this collection somewhere? It’d make testing easier.

**Comment by jdegoes** [comment]
@sellout Yes, you're right, that can be simplified.

**Comment by cryogenian** [comment]
Collection have had one document: 
```json
{
	"_id" : ObjectId("5554acaed86735b7268fd005"),
	"userId" : 8927524,
	"profile" : {
		"name" : "Mary Jane",
		"age" : 29,
		"gender" : "female"
	},
	"comments" : [
		{
			"id" : "F2372BAC",
			"text" : "I concur.",
			"replyTo" : [
				9817361,
				"F8ACD164F"
			],
			"time" : "2015-02-03"
		},
		{
			"id" : "GH732AFC",
			"replyTo" : [
				9654726,
				"A44124F"
			],
			"time" : "2015-03-01"
		}
	]
}
```

**Comment by jdegoes** [comment]
@cryogenian To be clear, you only need `SELECT DISTINCT` if you are using the array flattening operator `[*]`.

**Comment by cryogenian** [comment]
@jdegoes Thanks. Should I check if there `[*]` or it's ok to add `DISTINCT` to every search query?

**Comment by jdegoes** [comment]
@cryogenian It's better to check or otherwise the query will be slow and not distributed properly.

**Comment by sellout** [comment]
So, this shortened version of the query still exhibits the same issue, but should have a _bit_ less duplication. Mostly it’s here just to help me keep my sanity when debugging, but, @cryogenian, this should be equivalent (but faster and fewer dups).

```sql
select * from "/foo/foo/aabbc" where (
  "userId" LIKE '%female%' OR 
  "profile"."name" LIKE '%female%' OR 
  "profile"."age" LIKE '%female%' OR 
  "profile"."gender" LIKE '%female%' OR 
  "comments"[*]."id" LIKE '%female%' OR 
  "comments"[*]."text" LIKE '%female%' OR 
  "comments"[*]."replyTo"[*] LIKE '%female%' OR 
  "comments"[*]."time" LIKE '%female%')
```

**Comment by cryogenian** [comment]
@sellout Thanks, I've switched to this query already
