### ISSUE TITLE
Attempting to PUT to an existing file throws an error

### ISSUE THREAD

**Issue by garyb** [slamdata/slamengine#727]
At least I think that's what the problem is:

```
{  
   "errors":[  
      {  
         "detail":"com.mongodb.MongoCommandException: Command failed with error -1: 'target namespace exists' on server localhost:27001. The full response is { \"ok\" : 0.0, \"errmsg\" : \"target namespace exists\" }"
      }
   ]
}
```

This occurs when attempting to put the `index` file for a notebook after the initial notebook has been created.

**Comment by cryogenian** [comment]
I thought it's correct behavior.

**Comment by garyb** [comment]
PUT is supposed to update an existing resource as far as I know. That's the way it behaved in 1.3.4 too.

**Comment by jdegoes** [comment]
@sellout This ready to go or still waiting?

**Comment by sellout** [comment]
I think the PR is ready to go.
