### ISSUE TITLE
error from path parsing in planner

### ISSUE THREAD

**Issue by jdegoes** [slamdata/slamengine#729]
```
Physical Plan
`/' expected but end of source found
slamdata.engine.physical.mongodb.Collection$PathParser$.apply(collection.scala:46)
slamdata.engine.physical.mongodb.Collection$.fromPath(collection.scala:19)
slamdata.engine.physical.mongodb.MongoDbPlanner$$anonfun$13.apply(planner.scala:742)
slamdata.engine.physical.mongodb.MongoDbPlanner$$anonfun$13.apply(planner.scala:740)
... (3)
slamdata.engine.LogicalPlan$$anonfun$default$lzycompute$1$2.apply(logicalplan.scala:228)
slamdata.engine.LogicalPlan$$anonfun$default$lzycompute$1$2.apply(logicalplan.scala:222)
... (21)
```

**Comment by jdegoes** [comment]
Happens when the path doesn't go into any known database (I think), should try to improve the error message because this one is cryptic and useless.

**Comment by mossprescott** [comment]
See also #659.

**Comment by mossprescott** [comment]
I have a simple fix that improves the error message to this:

```
Physical Plan
path names a database, but no collection: ./zips
```

That's what you'll see, for example, if you cd to the mount location (say, `/local`), and run `select * from zips`. Hopefully that's suggestive enough that what's actually missing is a database name. Producing a more helpful message would involve actually going to MongoDB to check whether the partial path really does name a DB or not.

#659 provides an opportunity to do better.
