### ISSUE TITLE
Cannot MOVE a mount

### ISSUE THREAD

**Issue by garyb** [slamdata/slamengine#738]
I'm not sure if this is necessary for 2.0... @jdegoes? I guess you can "move" mounts by deleting them and then adding new ones.

We have an icon for it in the front-end currently, but if we're not going to do this I can hide it for mounts.

**Comment by jdegoes** [comment]
It should be possible, but doesn't need to be fixed tonight.

**Comment by garyb** [comment]
Ok, I'll hide the icon for now then.

**Comment by jdegoes** [comment]
No need to hide it, right? The backend will just error.

**Comment by garyb** [comment]
That's true. It says `/whatever/ not found` at the moment though, which is a little misleading.
