### ISSUE TITLE
Mount API sometimes requires a trailing slash in the path, sometimes does not

### ISSUE THREAD

**Issue by garyb** [slamdata/slamengine#739]
- `DELETE` requires the slash - `There is no mount point at /data2`
- `GET` does not - `There is no mount point at /data2/`

I'm not sure on `POST` and `PUT` yet, will update the issue when I get to those.

**Comment by garyb** [comment]
- `PUT` accepts either, but if you PUT with and without the slash it adds entries under both names to the `config.json`

Also the README states that `PUT`ting a mount that does not yet exist results in a 404, but currently it will create mounts too. I'm not sure which is the desired behaviour, as we allow `PUT`ting new files elsewhere.

- `POST` accepts either, but behaves differently depending on whether the trailing slash is there or not.

With no trailing slash `POST` will keep adding mounts even if a mount with the same name already exists. With the trailing slash the 405 is returned as intended.

(sorry!)

**Comment by jdegoes** [comment]
> Also the README states that PUTting a mount that does not yet exist results in a 404, but currently it will create mounts too. I'm not sure which is the desired behaviour, as we allow PUTting new files elsewhere.

If we allow PUTing new files, we should allow PUTing new mounts, for consistency.

**Comment by garyb** [comment]
- `DELETE` behaves a bit strangely also. It always works without the trailing slash, but it only works _with_ the trailing slash if the mount is defined _without_ a trailing slash in the `config.json`:

**Comment by sellout** [comment]
@jdegoes – yeah, PUT should create new mounts. I’ll update the README.

**Comment by sellout** [comment]
Mmmmm, but the current code looks like it should 404 when a PUT is submitted on a resource that doesn’t exist (which I think is wrong, but still looks like it _should_ fail.)

**Comment by sellout** [comment]
Oh, nevermind – same problem as with DELETE. *sigh*

**Comment by sellout** [comment]
Once #740 is merged, try this again – you’ll still need to be consistent with the trailing slash, but it should seem less random with the other bugs fixed.

**Comment by mossprescott** [comment]
The current implementation seems more complex than it needs to be.

Unless we have some particular need to be able to detect collisions, I don't think we need `POST` at all. That leaves just three methods:
- `GET`: which is safe (non-mutating)
- `PUT`: which is idempotent, and can create or update mounts
- `DELETE`: which is idempotent, and either deletes a mount or has no effect

A mount is always treated as a directory path internally, so I think it makes sense to normalize mount paths to have trailing slashes when the configuration is updated, and all of the operations should accept paths with trailing slashes. If the configuration is edited manually to have paths without trailing slashes, the API should still behave as if trailing slashes are there.

On the other hand, a path with no trailing slash can only possibly refer to the same mount as if the trailing slash were present, so I think we can safely also handle paths with no trailing slash by just behaving as if it were present.

**Comment by jdegoes** [comment]
> Unless we have some particular need to be able to detect collisions, I don't think we need POST at all. 

We'll support POST because it's an expected part of every REST API.

I do think semantically, for MongoDB a mount must always be a path, and such requirement should be enforced when attempting to mount a MongoDB cluster to a path.

Note that at some point, you might be able to mount a URL to a file; so in general I think whether mount is a file or directory depends entirely on the file system (e.g. MongoDB versus URL versus ???). 

In any case, I think all APIs should be very strict about directories: if there's a trailing slash, interpret as directory, if there is not, interpret as file, and produce errors as appropriate for the context.

**Comment by mossprescott** [comment]
Point taken on future possibilities for mounts. I'll just be strict about trailing slashes for MongoDB mounts.

@jdegoes: would you like to suggest a semantics for `POST`? What we're doing now seems mostly redundant with `PUT` as well as being inconsistent with the accepted definition of `POST`, which should "accept the entity enclosed in the request as a new subordinate of the resource identified by the Request-URI" ([RFC 2616](https://tools.ietf.org/html/rfc2616#section-9.5)).

**Comment by jdegoes** [comment]
> would you like to suggest a semantics for POST?

I am on board with changing it to become RFC compliant. In which case, the path must be the containing directory. The actual resource can be identified by, e.g. `X-File-Name`, which is fairly common, or if you can find some resource name convention even more common, I'd be in favor of that.

**Comment by mossprescott** [comment]
Working my way back to this and finding I still see no point in supporting `POST` and requiring a header for the name, when `PUT` is a perfectly adequate way of accomplishing that. POST is for adding stuff when you don't know the name for it, or when it won't end up getting a name of its own. That's not what we're doing here.

People might expect POST, but they won't expect it to require X-File-Name, so how much are we helping them?

**Comment by jdegoes** [comment]
No, actually, it's quite common to use X-Filename in AJAX POST, and many front-end developers are familiar with it, see, for example, [here](http://www.sitepoint.com/html5-ajax-file-upload/). File uploads are a perfect example of something that should fail if a resource already exists, and for which the common and accepted idiom is POSting it.
