### ISSUE TITLE
untitled notebook menu looks too big

### ISSUE THREAD

**Issue by sellout** [slamdata/slamengine#744]
It seems to overlap the content (can still see the first record, but slightly obscured). This happens in FF, Chrome, & Safari on Mac.
![slamdata_and_slamdata_slamdata_and_slamdata_slamengine_659_ _evaluator__fix_compiler_paths](https://cloud.githubusercontent.com/assets/33031/7913038/7e95de70-083a-11e5-9e3c-a160f43fd17d.png)

**Comment by cryogenian** [comment]
What's your Mac display resolution?

**Comment by jdegoes** [comment]
Moved to slamdata/slamdata#205
