### ISSUE TITLE
search misbehaves in empty notebook

### ISSUE THREAD

**Issue by sellout** [slamdata/slamengine#745]
On Firefox, I get the correct output:
![slamdata](https://cloud.githubusercontent.com/assets/33031/7913063/b4f06d6e-083a-11e5-84e1-4673c1168114.png)

But on Safari and Chrome, this happens:
![slamdata](https://cloud.githubusercontent.com/assets/33031/7913079/bb22594a-083a-11e5-86f2-8c25258dd3b7.png)

Navigated to /slamengine-test-01/zips, which took me to an untitled notebook, clicked on the magnifying glass at the bottom, selected /slamengine-test-01/zips from the drop-down, then typed “oulder” and clicked the play button.

**Comment by sellout** [comment]
Actually browser seems not to matter … if I go to /slamengine-test-01/zips, then just do the search, it fails, but if I do something else first (like a query), _then_ add a search, it works.

**Comment by cryogenian** [comment]
It fails only with first search cell in explore file resume.

**Comment by sellout** [comment]
Whoops, wrong repo.
