### ISSUE TITLE
Ordering issues

### ISSUE THREAD

**Issue by paf31** [slamdata/slamengine#747]
I was trying out your demo, and modified the city population demo to add an ordering:

```sql
SELECT DISTINCT state, SUM(pop) AS pop FROM "/slamengine-test-01/zips" WHERE city = UPPER(:name) GROUP BY state 
ORDER BY pop
```

but the ordering seems to be descending per-page instead of ascending globally.

Changing the ordering to `ORDER BY pop DESC` returns an ascending set per-page, but still, the results are not globally ascending, only ascending per-page.

**Comment by jdegoes** [comment]
There are likely two bugs here, will report the one on the front-end.

**Comment by jdegoes** [comment]
Thanks for reporting, btw. :smile:

**Comment by jdegoes** [comment]
We need to make sure that the offset/limit *query parameters* do not affect the skip / limit in the generated query, but only affect the subset of results returned. I'm not certain that's the case. Beyond that, we should verify that ASC / DESC is mapped correctly.

**Comment by mossprescott** [comment]
The offset and limit parameters in the HTTP request are applied to the MongoDB cursor when the result collection is read. In fact, they're only available for GET /data requests, not GET /query requests.

Running that query in the REPL, I seem to get correct results, but I also had a hard time getting more than one page of results. @paf31, what were you using for `:name`?

**Comment by paf31** [comment]
I was using the default value of `Boulder`. I was just modifying the demo on the website.

**Comment by sellout** [comment]
@paf31 – aren’t there only four results for that query?  They should all be on the first page, even without grouping.

**Comment by paf31** [comment]
That seems to be the case now, but there were three pages for the same query when I tried earlier today.

**Comment by sellout** [comment]
I blame the release gremlins. They’ve been everywhere today!

**Comment by sellout** [comment]
The ordering does still seem to be reversed on the demo page, but it’s correct in the REPL.

**Comment by sellout** [comment]
The order is coming back over HTTP correctly. I’m guessing the frontend is reversing the results as it reads the line-delimited JSON. I’m going to close this in favor of slamdata/slamdata#213.
