### ISSUE TITLE
query produces no results but should produce results

### ISSUE THREAD

**Issue by JeffACarr** [slamdata/slamengine#748]
```sql
SELECT * from "/slamengine-test-01/olympics" where (LOWER("type") LIKE '%skating%' OR LOWER("gender") LIKE '%skating%' OR LOWER("event") LIKE '%skating%' OR LOWER("country") LIKE '%skating%' OR LOWER("discipline") LIKE '%skating%' OR LOWER("sport") LIKE '%skating%' OR LOWER("city") LIKE '%skating%' OR LOWER("year") LIKE '%skating%')
```

**Comment by sellout** [comment]
I quickly got results from the in the REPL. Looking to see where we might be losing them.

**Comment by sellout** [comment]
Hrmm, I also got results on the demo site. Where did you not get results for this?

**Comment by sellout** [comment]
Oh, I have a guess! If you run a query, go to some random page, then run a new query in the same cell, it doesn’t reset the page # to 1. So if the new query has fewer pages of results, you might be off the end of the query.

But … this particular query has ~760 results, so unless you were on page 77+ of some other big query, you’re unlikely to have walked off the end. Does this sound familiar?

**Comment by jdegoes** [comment]
No, literally zero results were produced. As I recall, it completed, but was empty.

**Comment by jdegoes** [comment]
The document had a number of other cell types in it -- it wasn't just a standalone search. That might be causing the issue.

**Comment by sellout** [comment]
Ok. I tried to replicate that (but, randomly creating other cells, etc., so the odds of actually hitting the right conditions seems small), but couldn’t quickly.

In any case, it _seems_ like a front-end issue, so I’ll at least make a companion issue over there.

**Comment by jdegoes** [comment]
OK, sounds good. Could be search cell inserted through menu or search cell inserted as "next action" from some other cell.
