### ISSUE TITLE
numeric variables not working

### ISSUE THREAD

**Issue by jdegoes** [slamdata/slamengine#750]
With `year` set to `2000`:

```sql
SELECT DISTINCT country, COUNT(*) 
  FROM "/slamengine-test-01/olympics" 
  WHERE year = (:year + 0) AND type = 'Gold' 
  GROUP BY country
```

Error message:

```
Error in query: The variable :year should be convertible to type Coproduct(Int,Dec) but found: VarValue(2000)
```

**Comment by mossprescott** [comment]
`SELECT :year FROM ...` works fine, but `SELECT :year + 0 FROM ...` fails in variable substitution as shown. Should be a quick one. I can get to this later tonight.

**Comment by jdegoes** [comment]
Thanks, my goal's to get this working for tomorrow morning demos:

<http://104.236.166.167:8080/slamdata/notebook.html#/slamengine-test-01/SlamData+Olympics+Demo.slam/edit>
