### ISSUE TITLE
investigate possible performance issues with negative offset

### ISSUE THREAD

**Issue by jdegoes** [slamdata/slamengine#751]
Query:

```sql
out0 := SELECT DISTINCT country, COUNT(*) FROM "/slamengine-test-01/olympics" WHERE year = 2000 GROUP BY country
```

Then query on `out0` using the data API using offset = `-10` and limit = `10`.

**Comment by jdegoes** [comment]
Takes 30 seconds to return nothing.

**Comment by mossprescott** [comment]
Is returning nothing correct, and just being slow is the problem?

Taking 30 seconds to return a 500 seems to be the behavior of http4s when we throw an exception in a service method (which is obviously nonsense, see #741).

Should be another quick fix.

**Comment by jdegoes** [comment]
I don't think the data set should be empty. That said, I am not sure it is empty -- the semantics of offset = -10, limit = 10 should, logically speaking (*illogically* speaking?) return 0 results because you're starting at 10 entries prior to the first entry, and stopping 10 entries later, i.e. at the first entry.

That said I can't think of a possible universe in which it makes sense to allow the client to specify such strange combinations. That it does is a bug which is separately filed in the frontend.

So I'd consider the bug to be (a) the fact that it takes 30 seconds to return an empty data file (the data file is returned 200 and it's empty), and possibly (b) the fact that a negative offset is not rejected (which makes me suspect that negative limits probably aren't rejected either).
