### ISSUE TITLE
mongodb errors not returned in expected json format

### ISSUE THREAD

**Issue by jdegoes** [slamdata/slamengine#757]
This is what you get when MongoDB errors -- which does not comply with our normal return format and which 'crashes' the front-end:

```
An error occurred during evaluation: com.mongodb.MongoCommandException: Command failed with error 16702: 'exception: $concat only supports strings, not NumberLong64' on server ds045089.mongolab.com:45089. The full response is { "errmsg" : "exception: $concat only supports strings, not NumberLong64", "code" : 16702, "ok" : 0.0 }
```

**Comment by mossprescott** [comment]
Here's a request that demonstrates the problem:
```
curl -v -d 'select concat(pop, pop) from zips' -H "Destination: tmp999" -X POST http://localhost:8180/query/fs/local/test
```

This is a symptom of #757, or at least will be affected by the fix. Gonna hold off until @sellout' PR for that one.

**Comment by sellout** [comment]
FYI, this might be improved a bit by my #659 work.

**Comment by sellout** [comment]
Nevermind … it at least still misses this test case. But in general, I think I added a few places to handle errors rather than just joining with a Task[Response].

**Comment by mossprescott** [comment]
For the record, I meant to refer to #741 earlier.

**Comment by jdegoes** [comment]
Here's a separate regression, where we used to return the results in JSON but no longer do:

https://slamdata.supportbee.com/tickets/5782065

We need to have tests to verify that errors are returned in the right format to prevent these sorts of regressions.
