### ISSUE TITLE
support mongodb databases with spaces in their names

### ISSUE THREAD

**Issue by garyb** [slamdata/slamengine#760]
MongoDB itself doesn't allow this, but @jdegoes says it should be supported and abstracted by the back-end (slamdata/slamdata#249). We currently have an issue with this on the front-end, as the default name for directories is "Untitled Folder", so if you create a new directory in the top level of a mount that corresponds to a database, and attempting to create files within this database fails.

Uploading data to one of these invalidly-named database/directories results in a 500 error for a null pointer exception captured by Jetty or entirely empty response. Likewise, attempting to read or query stuff from an invalidly-named database also results in 500 errors with an NPE.

**Comment by jdegoes** [comment]
This should be generalized so that we simply escape all characters which the particular backend cannot support for some entity (excepting our path separator character, `/`).

**Comment by jdegoes** [comment]
This will probably close #818, too.

**Comment by mossprescott** [comment]
Here are the rules (see [the implementation](https://github.com/mongodb/mongo/blob/e484264ed64dfbe71be222b4be91d57e364e7a8c/src/mongo/db/namespace_string-inl.h#L57)):
- length between 1 and 63 characters
- none of the following: `\0`, `/`, `\`, `.`, space, `"`.
- on Windows, also `*`, `<`, `>`, `:`, `|`, `?`.

On the other hand, `$` is fine, so we probably need to just use a different approach than we do for collections.

Also, there's apparently no  way to quote db names in the shell, so some other patterns are hard to use, such as a name ending in `;`.

**Comment by mossprescott** [comment]
I'm open to suggestions for escaping schemes.

1) I believe `$dot` was suggested. I know something like this is used in Scala's name-mangling, and maybe elsewhere in the FP world. Is there a better reference than [this scala reflection code](https://github.com/scala/scala/blob/v2.11.5/src/library/scala/reflect/NameTransformer.scala#L39-56)? My concerns would be:
- Lack of a terminator making it potentially error-prone.
- Relatively un-compact. Remember we only have 63 characters to work with—`Now %1000 improved, at 1/2 price!` encodes to as much as 73.

2) We could use something like URL encoding, which is more compact, but not at all human-readable.

3) We invent a more compact encoding using `$`, say `/` -> `$f`, `<space>` -> `$s`, etc. That would save space and be slightly more readable than URL encoding. But we'd be making it up and I don't see this being very intuitive for as many characters as we need to escape.

@jdegoes, @sellout: opinions?

**Comment by jdegoes** [comment]
The most important things to me are the common characters, i.e. dot, space, and slash, so deleting a database with space in it (which "moves" it to `/.trash/my database/`) will be recognizable to, e.g. an admin looking at the database through some MongoDB tool.

Space is commonly encoded as `+`, which looks like it would work here; or one could choose `_` or `-`.

In any case, I'd use the uncommon valid characters for the more common cases noted above, and then use a bulkier, less readable encoding for everything else.

**Comment by mossprescott** [comment]
Good ideas. I'll play around and see what I can come up with that seems convenient.

Aside: If there's no mount at `/`, which is probably going to be common, then we have bigger problems with `/.trash/...`. Also, `moving` a db to a non-db path (and vice-versa) is going to be expensive (not a rename). Just things to think about if we're going down that path.

**Comment by jdegoes** [comment]
Sorry, I gave a relative path in the above example, not absolute. e.g., inside some cluster `foo`, deleting a database called `my database` would result in it being moved to the (absolute) path `/foo/.trash/my database`. The front-end does not use a global trash but instead moves each deleted resource into a trash within its parent.

> Also, moving a db to a non-db path (and vice-versa) is going to be expensive (not a rename). Just things to think about if we're going down that path.

Good. All the more reason to enforce permissions that prevent people from doing that. :smiling_imp:
