### ISSUE TITLE
add a mode for returning pure JSON result (result set wrapped in an array) for data API

### ISSUE THREAD

**Issue by jdegoes** [slamdata/slamengine#762]
We can use `application/json` for the pure JSON mode, and the newline-delimited mime type(s) for our current standard. This will make  it more faithful to specs and allow consumption of result sets "all at once" for use cases where that is appropriate. Front-end may need updating, /cc @garyb @cryogenian @puffnfresh .

**Comment by garyb** [comment]
I still haven't done slamdata/slamdata#87, but yep, that will need updating for this.

**Comment by mossprescott** [comment]
Subsumed by #763?
