### ISSUE TITLE
enhancements to data APIs

### ISSUE THREAD

**Issue by jdegoes** [slamdata/slamengine#763]
### CSV Enhancements

- [x] Client can specify column delimiter (`,`), row delimiter (`\n`), quote character (`"`), and escape quote character (`"`). **These should be media types.**

### JSON Enhancements

- [x] Client can specify whether results should be wrapped in array, or newline-delimited. We can use the `Accept` header type to distinguish between them, by assuming `json` is array wrapping, and the newline-delimited mime types, etc.

### Both Enhancements

- [x] Client can elect to download ZIP (compressed resource) instead of raw resource.
- [x] Client can download folder, whether that is a database, multiple databases, cluster, multiple clusters, or root. In multi-resource cases, the results are incrementally zipped and transmitted back to client (need a scalaz-stream ZIP wrapper or the `OutputStream` adapter).
- [x] Client can specify which disposition it accepts (including file name) in `Accept` header, e.g.:
    ```
    Accept:text/csv;disposition="attachment; filename=data.csv"
    ````
- [x] Client can supply headers via an additional query param (in case the client is unable to control request headers, as is the case in the browser for download links).

**Comment by jdegoes** [comment]
See [here](https://github.com/slamdata/slamdata/issues/260) for context.

**Comment by jdegoes** [comment]
@mossprescott See above for added feature (accept disposition).

**Comment by jdegoes** [comment]
Let's do:

```
?request-headers=<JSON Object>
```

Assuming signoff from @garyb. This lets us add (eventually) `response-headers` for those times when the browser needs to tweak the response headers to workaround some other limitations.

**Comment by garyb** [comment]
:+1:
