### ISSUE TITLE
web: allow startup even if specified port is taken

### ISSUE THREAD

**Issue by jdegoes** [slamdata/slamengine#765]
If the port is taken, then any freely available port should be used, but we should issue a warning to the user that the port specified in the configuration file is not being used (we should display that port, as well as the actual port the server is running under).

**Comment by jdegoes** [comment]
@mossprescott  This is the last outstanding 2.1 ticket, @-reply me when it's in so I can cut the 2.1 release.

**Comment by mossprescott** [comment]
@jdegoes PR ready for you.
