### ISSUE TITLE
slamengine fails on windows

### ISSUE THREAD

**Issue by jdegoes** [slamdata/slamengine#767]
![slam_error1](https://cloud.githubusercontent.com/assets/156745/8039587/18242ea6-0dc8-11e5-9212-c05fe5d0cf4b.png)

**Comment by jdegoes** [comment]
See [here](https://slamdata.supportbee.com/tickets/5571885) for more information, including log (which should not be posted since it contains PII).

**Comment by mossprescott** [comment]
I believe this was fixed in 80a34590bfe9d6f131e238c817cf3cba863a832e (so, 2.0.1, apparently).

**Comment by mossprescott** [comment]
@sellout: any idea if this is still an issue?

**Comment by sellout** [comment]
No, I think this should be fixed in that commit … however, it’s probably not a bad idea to catch any exception there and just ignore it … right? 😝
