### ISSUE TITLE
allow any sql expression for variables in template queries

### ISSUE THREAD

**Issue by jdegoes** [slamdata/slamengine#769]
We can remove the type inference altogether if there is a way to get numbers and booleans from strings, which may lead to a simpler design that substitutes variables before the analysis / typing / etc. is run.

**Comment by jdegoes** [comment]
On further thought, I think we require SQL expressions, and thus do away with the need for type inference. Then we can substitute on the SQL AST before any phases are run.

**Comment by mossprescott** [comment]
See slamdata/slamdata#291.

**Comment by mossprescott** [comment]
See slamdata/slamdata#192.
