### ISSUE TITLE
non-root mounts are listed with absolute paths in metadata/

### ISSUE THREAD

**Issue by garyb** [slamdata/slamengine#781]
Config:
```
{
  "mountings": {
    "/foo/": {
      "mongodb": {
        "connectionUri": "mongodb://localhost:27001"
      }
    },
    "/foo/bar/": {
      "mongodb": {
        "connectionUri": "mongodb://localhost:27002"
      }
    }
  }
}
```
Gives this response when requesting `/metadata/fs/foo/`:
```
{
  "children": [
    {
      "name": "local",
      "type": "directory"
    },
    {
      "name": "test",
      "type": "directory"
    },
    {
      "name": "foo/bar",
      "type": "mount"
    }
  ]
}
```

**Comment by mossprescott** [comment]
@sellout: when you took over this code, nothing was being done to deal with this. I think the "right" fix involves building a NestedBackend at each level in the hierarchy implied by the mount paths, but a quicker fix would probably be to just put some handling of multi-node paths in NestedBackend. Make sense?

**Comment by jdegoes** [comment]
We need more tests in this code, these kinds of issues should not be making it to the front-end team.

Listing the children of a path should only ever return *immediate* children.

**Comment by jdegoes** [comment]
> I think the "right" fix involves building a NestedBackend at each level in the hierarchy implied by the mount paths

^^^ Yes, that sounds right, the config could / should even reflect that structure, probably (as in the config snippet I gisted the other day).

**Comment by garyb** [comment]
Sorry, there's another thing too, related I assume. A mounting like this:
```
    "/baz/quux/": {
      "mongodb": {
        "connectionUri": "mongodb://localhost:27001"
      }
    }
```
Doesn't appear when getting `/metadata/fs/` (no `baz` entry).

**Comment by jdegoes** [comment]
^^^ Above needs a test, too.

**Comment by sellout** [comment]
As far as changing the config format … what is required to make that reasonable for users? Should we fall back to parsing the old config, and then save it as the new config?

**Comment by jdegoes** [comment]
@sellout We should probably start embedding version numbers in the config. For now, it's OK to read and ignore errors, forcing users to re-create the config; or if it's simple enough and not going to create much technical debt, read the old format (and the new format) and write only the new format.

**Comment by jdegoes** [comment]
> Sorry, there's another thing too, related I assume. A mounting like this:

I think if we do this write, this format will be invalid, you'll have to mount "baz" and then beneath "baz", you'll have to mount "quux". This reflects the logical hierarchies of file systems, whereby you cannot actually mount "baz/quux" and "baz/foo" as independent; both need to reside inside the "baz" file system, and do so in the code. One could consider having shorthand config notation for such cases, e.g. "baz/quux" implicitly mounts "baz" and then mounts "quux" in "baz", etc., but that's a fancy feature we don't need since we hope users will configure through the GUI and not by hand.

**Comment by sellout** [comment]
@garyb – The config in your first example isn’t valid (and, once we have the new config format, it should be impossible to create). You can’t have a Mongo instance mounted inside a Mongo instance.

That said, I did replicate both issues with a valid config, so it’s just FYI and I still have bugs to fix 😉

**Comment by garyb** [comment]
Ah ok, that's what I was attempting to find out with the above! I'll add something to the frontend that should make it impossible.
