### ISSUE TITLE
duplicate entries appearing in /metadata for nested mounts

### ISSUE THREAD

**Issue by garyb** [slamdata/slamengine#785]
I know this isn't really supported yet, but thought I'd open this for consideration anyway. When doing this, parent directories of the nested mount contain duplicate entries. When you have nested mounts like:

``` json
{
  "mountings": {
    "/foo/": {
      "mongodb": {
        "connectionUri": "mongodb://localhost:27001"
      }
    },
    "/foo/bar/baz/": {
      "mongodb": {
        "connectionUri": "mongodb://localhost:27002"
      }
    }
  }
}
```
A duplicate entry appears for each part of the overlapping path. So for `/metadata/fs/`:
``` json
{
  "children": [
    {
      "name": "foo",
      "type": "mount"
    },
    {
      "name": "foo",
      "type": "directory"
    }
  ]
}
```
And if the `foo` mount has a `bar` directory as well, `/metadata/fs/foo` gives us:
``` json
{
  "children": [
    {
      "name": "bar",
      "type": "directory"
    },
    {
      "name": "test",
      "type": "directory"
    },
    {
      "name": "bar",
      "type": "directory"
    }
  ]
}
```

**Comment by sellout** [comment]
This is really a part of #781, although I think it’s worth having a separate ticket for the symptom.
