### ISSUE TITLE
Sbt test fails on some downloads. and sbt 'project core' onejar also doesnt work.

### ISSUE THREAD

**Issue by ahmedulde** [slamdata/slamengine#803]
I am not sure if this is a bug or my mistake but i need this slam engine so i am intrested in getting started with it. Please have a look at screen shots.
![sbt test](https://cloud.githubusercontent.com/assets/4686444/8332967/5f8b5d60-1a56-11e5-9326-b900dcb04be0.PNG)
![sbt project core one jar](https://cloud.githubusercontent.com/assets/4686444/8332969/61a629b8-1a56-11e5-9abd-17d21214f433.PNG)

**Comment by mossprescott** [comment]
I'm not sure what's going wrong with downloading dependencies.

The second problem is most likely just that you need to use a different quote character in a Windows CMD shell. Try `sbt "project core" oneJar`.

I notice that we don't include an `sbt.bat` script with the project. Do you have `sbt` installed on this system? If so, what version? Or are you using something like cygwin? I'm just trying to understand how the build script is running.

**Comment by ahmedulde** [comment]
I have sbt 0.13.8. installed. double quotes did work. i got the build success. I am not using cygwin.I keep getting this warning i dnt know if it helps.
![jvm ignoring maxpermsize](https://cloud.githubusercontent.com/assets/4686444/8336922/7a8ff488-1a6d-11e5-9dda-2805c686c40b.PNG)

**Comment by mossprescott** [comment]
That warning comes from using an earlier sbt launch script with Java 8, which doesn't cause any other problems that I know of.

So are you still having problems with the build or with running slamengine?

**Comment by ahmedulde** [comment]
Yes. I am able to run queries but somehow i feel the query has some error. please see the highlighted text in image below. right side is mongo shell and left is REPL. Please see the difference in query and its output. m101 is the db and hw1_1 is the collection with one small document.
![query error](https://cloud.githubusercontent.com/assets/4686444/8338208/59580d84-1a75-11e5-8c81-4fbfe22f5cd6.PNG)

**Comment by ahmedulde** [comment]
After i restarted several times and tried i got the correct answer. But the above image is what i saw initially. I dont understand why this difference by just restarting? Below is what i got after i restarted the engine.
![correctop](https://cloud.githubusercontent.com/assets/4686444/8338497/024ae1e0-1a77-11e5-85fb-53eb37e7d5a1.PNG)

**Comment by jdegoes** [comment]
You have to `cd` into the right path in order to run queries like `FROM m101`. Otherwise, you have to specify the full path to the file.

Please try the `ls` and `cd` commands.

**Comment by jdegoes** [comment]
By the way, for support issues (and not bug reports), we prefer people send an email to support@slamdata.com. Thanks!
