### ISSUE TITLE
REPL: `ls` output not formatted

### ISSUE THREAD

**Issue by mossprescott** [slamdata/slamengine#805]
The raw `FilesystemNode`s are being displayed in the REPL now. At a minimum, we should pull out and display just the path. It would be great to get rid of the leading `./`s. Possibly we should also somehow indicate which paths are mounts?

```
💪 $ cd /
💪 $ ls
FilesystemNode(./read-only/,Mount)
FilesystemNode(./nearest/,Mount)
FilesystemNode(./local/,Mount)
FilesystemNode(./sd/,Mount)
💪 $ cd local/test
💪 $ ls
FilesystemNode(./unicode,Plain)
FilesystemNode(./tmp/,Plain)
FilesystemNode(./days,Plain)
FilesystemNode(./zips,Plain)
```

**Comment by jdegoes** [comment]
`ls` should just show the children, but `ls -l` can show more extensive display results, which show the type and other metadata.

**Comment by mossprescott** [comment]
#813 does not add a `-l` option, so maybe doesn't close this after all.
