### ISSUE TITLE
unexpected error: Invalid file from SlamEngine

### ISSUE THREAD

**Issue by jdegoes** [slamdata/slamengine#808]
When evaluating this query in the online demo environment:

```
select distinct count(*) as count, type, country from "/slamengine-test-01/olympics" WHERE UPPER(sport) = UPPER(:sport) GROUP BY country, type order by count desc
```

One gets the error: "Invalid file from SlamEngine", which is not only incorrect (the file exists), but is also a new regression due to recent updates (presumably in SlamEngine).

**Comment by mossprescott** [comment]
Seems to affect any query at the moment. I can see the query request coming back ok, and then no `/data` request is sent for the result.

The only thing I can spot is the path in the response is relative (starts with `./`), but in my case contains the whole path (so, relative to `/`, if anything) which could be confusing the front-end, maybe?

**Comment by jdegoes** [comment]
@garyb can you also take a look?

**Comment by garyb** [comment]
Yeah, this is down to the relative path. Can we make the path absolute in the back-end, since it is relative to `/` anyway? If it's a pain, no worries, it won't be hard to fix in the front-end, just thinking having it as absolute might avoid future confusion.

**Comment by jdegoes** [comment]
The docs say this:

> This API method returns the name where the results are stored, as an absolute path, as well as logging information.

So this is a new regression, probably related to the recent `Path` changes.
