### ISSUE TITLE
mongodb: temp collection left behind if destination path exists

### ISSUE THREAD

**Issue by mossprescott** [slamdata/slamengine#821]
If the client specifies a path for the result of a query (e.g. when using the POST /query API), and there is already a collection there, then a runtime error occurs and the temporary collection is left behind.

```
$ curl -i -X POST -d 'select pop from zips' -H "Destination: tmp000" http://localhost:8180/query/fs/local/test?limit=10
HTTP/1.1 200 OK
...
$ curl -i -X POST -d 'select pop from zips' -H "Destination: tmp000" http://localhost:8180/query/fs/local/test?limit=10
HTTP/1.1 500 Internal Server Error
...
{"error":"uncaught: com.mongodb.MongoCommandException: Command failed with error -1: 'target namespace exists' on server localhost:27017. The full response is { \"ok\" : 0.0, \"errmsg\" : \"target namespace exists\" }"}
```
After the second attempt, a collection named something like `tmp.gen_284215a4_0` is left behind, containing the result of the query.

**Comment by mossprescott** [comment]
@jdegoes: do you remember what the behavior was supposed to be when running a query with a specified destination? Is it supposed to overwrite with no warning?

I have a feeling that it may have changed at some point.

**Comment by jdegoes** [comment]
There are three possible semantics, each useful in a different class of circumstances:

1. **Overwrite**. Useful for things like the SlamData front-end, when the output name itself is designed to be temporary, but under control of the user / client.
2. **Error**. Useful if you do not expect anything to exist there, and want to fail fast should something come into existence with that name before the query has completed.
3. **Append**. Useful for incremental queries which operate on new data and pipe their results into an ever-growing collection of processed results.

In no case, of course, should temporary files be left around.

I'd suggest we adopt one semantic (e.g. (1)), and add a ticket to support all of them, e.g.; by media type on the `Destination` header or something like that.
