### ISSUE TITLE
push projections into groups to minimize data being grouped

### ISSUE THREAD

**Issue by jdegoes** [slamdata/slamengine#831]
Currently, we always (almost always?) push `$ROOT`, even when we only need a single field. We should only group what we actually require to minimize the size of the data being grouped.

An additional consideration is that `COUNT(*)` and similar, which do not reference any data, should not result in the capturing of any data.

**Comment by mossprescott** [comment]
Can you give an example? I'm not seeing `$ROOT` being pushed in any of the cases I try, and `COUNT(*)` and all the other aggregate functions don't seem to result in any pushing, either. Probably there's a pattern I'm not using.

What I do see which is in the same ballpark is cases where we *project* `$ROOT` under a temp name, and then in a subsequent op refer only to one or two fields from it. That's a consequence of the way we rewrite things into `$project`, and is an interesting problem. Not sure whether we want to try to rewrite smarter, or optimize the WorkflowOp after it's built (when we could collapse temps with the same source, and so on.)

**Comment by jdegoes** [comment]
Try a `COUNT(*)` on a JOIN or something. The join key computation for the LHS definitely pushes root.

Have you also tried things like `COUNT(_id)`, `SUM(pop)`, etc., to make sure we're never $pushing the ROOT and then extracting out only one or two fields?

> What I do see which is in the same ballpark is cases where we project $ROOT under a temp name, and then in a subsequent op refer only to one or two fields from it.

It'd be nice to track this too as a separate optimization since it will have an impact on performance. The earlier and more completely we can reduce the payload, the faster MongoDB will exec these pipelines.

**Comment by mossprescott** [comment]
Don't know what I was trying earlier, but I can make this happen by just combining any aggregate function with a simple field projection, with no explicit grouping. For example:

```sql
select avg(pop), city from zips
```

```json
    {
      "$group": {
        "0": { "$avg": "$pop" },
        "__tmp0": { "$push": "$$ROOT" },
        "_id": { "$literal": null }
      }
    },
    { "$unwind": "$__tmp0" },
    { "$project": { "0": "$0", "city": "$__tmp0.city" } },
```
Interestingly, this actually performs pretty well, although it will run into the 16 MB limit on BSON documents if the data set gets much larger.

On the other hand, the very similar query `select avg(pop), length(city) from zips` performs very poorly, probably because the $Unwind op gets inlined into mapReduce.

**Comment by mossprescott** [comment]
One more observation:

Adding a filter (even if it matches everything) will cause the planner to *not* push `$$ROOT`, *and* it also does not inline the $unwind into mapReduce, but does a separate `aggregate` step after:
```sql
select avg(pop), length(city) from zips where state != 'ZZ'
```

```
├─ $Match
│  ╰─ Doc
│     ╰─ Expr(BsonField.Name("state") -> Neq(Text(ZZ)))
├─ $SimpleMap
│  ├─ Map({ "1": _.city.length, "__tmp0": _.pop })
│  ╰─ Scope(Map())
├─ $Group
│  ├─ Grouped
│  │  ├─ Name(0 -> Document{{$avg=$__tmp0}})
│  │  ╰─ Name(1 -> Document{{$push=$1}})
│  ╰─ By(Literal(Null))
╰─ $Unwind(DocField(BsonField.Name("1")))
```

This query runs in 1.4s for me and uses minimal temp space. We might get a large improvement just by *not* inlining $unwind ops that can be done in the pipeline instead. Or it could be that there's a bug in the translation of $unwind to JS...
