### ISSUE TITLE
How does one connect to a mongodb instance via SSL

### ISSUE THREAD

**Issue by taxilian** [slamdata/slamengine#842]
We would like to look into using slamdata / slamengine, but I don't see any way to use a SSL connection to connect to mongodb; is there one that I'm missing somewhere?

**Comment by jdegoes** [comment]
@taxilian SlamData uses MongoDB Connection URIs, so the documentation [here](http://docs.mongodb.org/manual/reference/connection-string/) should be quite helpful, because it describes using SSL with the Connection URI format.

The MongoDB folks can also help you set this up, if you like. Hope that helps!

**Comment by taxilian** [comment]
I appreciate the quick response.  The problem, though, is that in order to use SSL connections you need to be able to provide a client certificate, client key, and SSL CA key... that doesn't go in the connection URL, so this still doesn't answer or solve the issue :-/

**Comment by jdegoes** [comment]
Hi @taxilian, you can find more detailed instructions for what you need to do with SlamEngine [here](http://mongodb.github.io/mongo-java-driver/3.0/driver/reference/connecting/ssl/). SlamEngine is the SlamData backend and uses the Java client library. So while `ssl=true` is all you need to do on the front-end, you will have to give the JVM backend access to the server's SSL. All of the documentation you need to do this should be contained in the [above link](http://mongodb.github.io/mongo-java-driver/3.0/driver/reference/connecting/ssl/). As part of a commercial support license or hourly consulting, the SlamData company driving this project can also get you up and running if you'd like more assistance.
