### ISSUE TITLE
expose `value` nesting in api

### ISSUE THREAD

**Issue by garyb** [slamdata/slamengine#849]
I encountered this while testing the front-end (slamdata/slamdata#349), but I think it may be slamengine related:

1. Click on Olympics data set, result opens in explore.
2. Click on Query next action. Add `WHERE year > '1900'` clause. The result set is returned as `out1`
3. Click on the Query next action, query `SELECT * FROM out1` is generated, and the result set is returned as `out1`.
4. Click on the Search next action, search for the letter ‘e’. Result set is filtered and returned as `out3`.
5. Add a Markdown cell with content `sport = _____ (Ice Hockey)`
6. Click on the next action to insert a Query cell with query `SELECT DISTINCT COUNT(*) AS count, country, type FROM "out3" WHERE sport = :sport GROUP BY country, type ORDER BY count DESC`
7. No result

If you change `out3` to `out1` or the olympics dataset it returns results succesfully. There are also definitely "Ice Hockey" results in `out3`.

**Comment by jdegoes** [comment]
@garyb Thanks! Have you confirmed that the front-end is sending the appropriate requests, and correctly interpreting the responses?

**Comment by garyb** [comment]
Yep, as far as I can tell it's doing what it is supposed to. When running the last query, the requests go like this:

- DELETE `out5`
- POST `SELECT DISTINCT COUNT(*) AS count, country, type FROM "out3" WHERE sport = :sport GROUP BY country, type ORDER BY count DESC` with `Destination` header `/data1/aaaa/Untitled Notebook.slam/out5` and parameters `?sport=%27Ice%20Hockey%27`
- GET `out5?q=SELECT%20COUNT(*)%20as%20total%20FROM%20%22%2Fdata1%2Faaaa%2FUntitled%20Notebook.slam%2Fout5%22` - this returns an empty result with a 200 status
- GET `out5?offset=0&limit=10` - another empty result

And we're getting this query back from slamengine when we POST to `out5`:
``` javascript
db.getCollection("Untitled Notebook\.slam.out3").aggregate(
  [
    { "$match": { "sport": "Ice Hockey" } },
    {
      "$project": {
        "__tmp2": { "country": "$country", "type": "$type" },
        "__tmp3": "$$ROOT"
      }
    },
    {
      "$group": {
        "count": { "$sum": { "$literal": NumberInt(1) } },
        "__tmp2": { "$push": "$__tmp2" },
        "_id": { "0": "$__tmp3.country", "1": "$__tmp3.type" }
      }
    },
    { "$unwind": "$__tmp2" },
    {
      "$project": {
        "count": "$count",
        "country": "$__tmp2.country",
        "type": "$__tmp2.type"
      }
    },
    { "$sort": { "count": NumberInt(-1) } },
    {
      "$group": {
        "__tmp4": { "$first": "$$ROOT" },
        "__sd_key_0": { "$first": "$count" },
        "_id": { "count": "$count", "country": "$country", "type": "$type" }
      }
    },
    { "$sort": { "__sd_key_0": NumberInt(-1) } },
    {
      "$project": {
        "count": "$__tmp4.count",
        "country": "$__tmp4.country",
        "type": "$__tmp4.type",
        "_id": false
      }
    },
    { "$out": "tmp.gen_0" }],
  { "allowDiskUse": true });
db.tmp.gen_0.find();
```

So it all seems sensible to me at least, aside from the empty 200 responses. The generated query looks the same when I change over to `out1` aside from the collection path change. Requesting the `out3` file directly returns a non-empty result set, and it contains entries for `Ice Hockey`.

**Comment by mossprescott** [comment]
The search query is returning its result under `value` (the tip-off is `_id` appearing in the result). Changing the query to this makes it work: `SELECT DISTINCT COUNT(*) AS count, value.country, value.type FROM "out3" WHERE value.sport = :sport GROUP BY value.country, value.type ORDER BY count DESC`.

The search query that results in a plan leaving its result under `value` is `select *` with a filter that can't be translated to a selector (`lower(foo) like '%e%', in this case):
```sql
SELECT * from "/demo/Untitled Notebook.slam/out1" where (LOWER("type") LIKE '%e%' OR LOWER("gender") LIKE '%e%' OR LOWER("event") LIKE '%e%' OR LOWER("country") LIKE '%e%' OR LOWER("discipline") LIKE '%e%' OR LOWER("sport") LIKE '%e%' OR LOWER("city") LIKE '%e%' OR LOWER("year") LIKE '%e%')
```

I believe we should be adding a map-reduce step at the end of this query to project `value` back to the root, but it's not happening here. Does that sound right, @sellout?

**Comment by jdegoes** [comment]
@mossprescott Unfortunately, map/reduce will inevitably end up in value.

**Comment by mossprescott** [comment]
@jdegoes: Right, thanks for pointing out the obvious ;-) And until we have collection metadata, we can't fix that. So the problem is that the API hides the `value` field when everything is nested under it, which is nice for readability (and was originally implemented for the admin UI), but confuses the front-end. The simple fix would be to just get rid of that and let the search result show up as `value.city`, `value.country`, etc.

**Comment by jdegoes** [comment]
> The simple fix would be to just get rid of that and let the search result show up as value.city, value.country, etc.

Let's do that for now.

**Comment by mossprescott** [comment]
After looking into it, it appears that we don't (and probably never did) hide the `value` prefix in the API. The data's definitely being returned to the client with it intact, so something in the front-end must be stripping it off.

<img width="1241" alt="screen shot 2015-07-27 at 09 34 15" src="https://cloud.githubusercontent.com/assets/6147371/8911650/b8f67898-3442-11e5-89fb-a2306c5d6179.png">

@garyb Can you try to track that down on the client side and re-open this if it turns out there's something wrong in the API?

**Comment by garyb** [comment]
Here's the culprit: https://github.com/slamdata/slamdata/blob/f5797430bbc451e9d9b33c0d7959afd8c28e09fc/src/Api/Query.purs#L162

**Comment by garyb** [comment]
@jdegoes so this wasn't a bug in the API, but do we want to expose the `value..value` case that is being hidden by the front-end? It's probably not great from a UX point of view. Not that I'm trying to make more work for you @mossprescott :smile:.

If it's possibly a longer term thing / fine as it is then fair enough! Just thought I'd ask.

**Comment by jdegoes** [comment]
@garyb I don't think we can lie about the data without running into the sorts of problems we currently are. It's definitely considered a bug in the backend that we nest data inside `value`, there are at least two open tickets for that; albeit solving one of which is not that easy (we have to do it outside MongoDB which requires metadata that we don't yet have a mechanism for storing).

So let's fix the issue in the front-end and modify the testing script to reference the actual data.

**Comment by garyb** [comment]
Ok, sounds good. And yeah, I did mean "fixing" the backend rather than the frontend for this, as like you say there's not really a workaround we can do there.

**Comment by jdegoes** [comment]
Well, the front-end pretends the data is not nested in `value`, which means a user queries against the unnested result, and gets back (unexpectedly) the empty result set. So let's turn off the magic on the front-end, it won't be needed anyway when the above mentioned bugs are fixed.

**Comment by sellout** [comment]
@garyb: I am concerned about the `value.value.*` … can you make a separate issue for a query that triggers that? We should be able to get everything down to at least `value.*`, and if the shape is known (IE, no `select *`) we should be able to eliminate `value.*` (even if there is a mapReduce).

As far as the front-end, can the stripping of `value.` be moved closer to the display, so that it pretties up output, but doesn’t affect further queries that depend on the true structure?

**Comment by jdegoes** [comment]
> As far as the front-end, can the stripping of value. be moved closer to the display, so that it pretties up output, but doesn’t affect further queries that depend on the true structure?

It can't, otherwise the user would query for data having the wrong structure. :cry: 

As for doubly-nested value, I thought we had a ticket for that, but I couldn't find it.

**Comment by garyb** [comment]
> I am concerned about the `value.value.*` … can you make a separate issue for a query that triggers that?

I think it may have been @cryogenian who wrote the code for that case - I wasn't aware of this `value` flattening at all previously. Do you have an example Maxim?

**Comment by cryogenian** [comment]
Sorry for delay. 
Nested `value.value.*` will appear when user will search something in search results, there is no one query to produce it. 
i.e. first search cell contains `cha` and second `fin`
