### ISSUE TITLE
incorrect formation of paths on windows

### ISSUE THREAD

**Issue by jdegoes** [slamdata/slamengine#858]
```scala
  def defaultPath: Task[String] = Task.delay {
    import scala.util.Properties._

    val commonPath = "SlamData/slamengine-config.json"

    if (isWin)
      envOrElse("LOCALAPPDATA", propOrElse("user.home", ".")) + commonPath
    else
      propOrElse("user.home", ".") +
        (if (isMac) "/Library/Application Support/" else "/.config/") +
        commonPath
  }
```

On Windows, there is no path separator between the `commonPath` and whatever crap comes out of the environment variable.

Note that such bugs cannot happen with a library abstraction like [purescript-pathy](http://github.com/slamdata/purescript-pathy). :wink:

**Comment by mossprescott** [comment]
Indeed, which makes this maybe the perfect time to switch to my Scala port of pathy (http://github.com/mossprescott/slamengine-pathy).

**Comment by sellout** [comment]
👍🏾

**Comment by wemrysi** [comment]
Even if there was a separator, would it work? Aren't path separators implementation specific (i.e. windows uses "\").

**Comment by jdegoes** [comment]
You can use `File.separator` / `File.separatorChar`. Although pragmatically speaking, Windows does support forward slashes just fine.

**Comment by jdegoes** [comment]
pathy should probably support custom path separator chars as part of the encoding / decoding process. The whole notion of escaper needs beefing up.

**Comment by wemrysi** [comment]
Agreed, I'll work to fortify pathy then integrate it to fix this issue. Then we can decide when to replace `engine.fs.Path` (#155).
