### ISSUE TITLE
mongodb: test connection when adding/editing a mount

### ISSUE THREAD

**Issue by mossprescott** [slamdata/slamengine#863]
Currently, when a mount is added or edited through the API, we "validate" the configuration (which amounts to parsing the URI), but do not perform a connection test. Running `Backend.test` on the config would uncover problems with connectivity and authentication earlier.

Also, the connection test does not currently do any write operations. Adding that would make the test even more robust. See https://github.com/slamdata/slamengine/blob/6f275ac8f3c33bcfb9131535884818a5937b11cc/core/src/main/scala/slamdata/engine/backend.scala#L353-L358.

**Comment by jdegoes** [comment]
We should *never* successfully mount a new source unless that source is useful for queries, which implies the mounting operation should always perform validation necessary to ensure some minimally useful level of functionality. As demonstrated in this ticket, currently there is no validation which can result in the creation of completely invalid mounts, and no way to pass useful useful information back to the user as she is mounting a new source.

**Comment by mossprescott** [comment]
Per @jdegoes: 
> Here are things I have seen:
> * No credentials supplied
> * Wrong credentials supplied
> * Correct credentials, but wrong auth database (path)
> * Correct credentials, and no auth database (path)
> * Correct credentials, right auth database, user only has read perms, not write
> * Wrong server and / or port

**Comment by jdegoes** [comment]
Btw, you can test for "wrong server / port" doing something like:

```scala
\/.fromTryCatch {
  new Socket (serverAddress, serverPort).close()
}
```

I'm not sure you can differentiate between that case and "wrong cred" and / or "wrong auth db" using the Mongo client (but maybe).

In any case, user specifying auth but NOT specifying auth db is probably wrong (always?). Mongo's error codes can be extracted to refine the error type / message we return to the user. We want really helpful 1-liners that can be displayed inline in the GUI to guide the user through the correction process.

**Comment by jdegoes** [comment]
Finally, we should have the ("no junk") property that it is not possible to create or update a mount through the API unless it validates.

**Comment by mossprescott** [comment]
We already have the "no junk" property, with regard to _validate_, which just parses the URI. This ticket is about extending that property to _testing_ the connection.

An important distinction, however, is that _validity_ is stable, in that it is a pure function of the connection URI, while _testability_ can only be evaluated relative to the current state of the world. Concretely, if you take down, move, or modify a MongoDB instance after creating a configuration that refers to it, you've effectively introduced junk behind our backs.

Conversely, up front, mandatory testing of connections means that it will be impossible for users to add connections that are currently unavailable, even if they know that those connections will be available when they want to use them. I don't think this is a problem we need to solve right now.

**Comment by jdegoes** [comment]
That's not a useful definition of *validate*, since we don't care at all about well-formedness of URIs, we *only* care about connecting to MongoDB. Testing for well-formedness is merely one strategy to help aid connection to MongoDB (one which is not currently even used because the front-end only generates well-formed URLs).

In any case, I have no problem restricting this to mongo clusters that are up and running and accessible at the moment of definition. Because a user who "knows" a connection will be available later is almost certainly wrong about some parts of the URI.

**Comment by mossprescott** [comment]
I'm not defending the semantics, just describing it :wink: 

And I only bring up the latter point because experience shows that users will eventually demand that feature (even though you are correct about them getting it wrong 90% of the time.)

**Comment by jdegoes** [comment]
If they demand it, I'll schedule it for Enterprise. :smiling_imp:
