### ISSUE TITLE
Manual restart of slamengine required after adding or removing database

### ISSUE THREAD

**Issue by jonsterling** [slamdata/slamengine#865]
**NOTE**: This issue only occurs in the bundled version of SlamData that is downloaded from our website. I cannot reproduce with my own build and the latest `slamengine` jar.

When I mount a database, it does not appear in the list unless I manually quit `SlamData.app` (which I assume is what is running `slamengine`) and restart it. The same thing happens when removing a database.

**Comment by jdegoes** [comment]
Need someone to take a look at this ASAP.

**Comment by mossprescott** [comment]
It looks like the API server isn't stopping when it should, which is causing the new instance to pick a random port when it starts up (this is internal to the backend Java process). At least that's what I'm seeing when I run from a shell:
```
$ /Applications/SlamData\ 2.1.5.app/Contents/MacOS/JavaApplicationStub 
Embedded server listening at port 8180
Press Enter to stop.
Requested port not available: 8180; Address already in use
Embedded server listening at port 51048
Press Enter to stop.
Server restarted on port 8180
```

After that, there is still a server running on 8180, with the old config, and there's nothing listening on the new port as far as I can tell.
