### ISSUE TITLE
It takes 30s for a bad mount configuration to be rejected

### ISSUE THREAD

**Issue by jonsterling** [slamdata/slamengine#877]
As of #863 / #870, the backend now verifies that it can connect to a mount before saving it; this is useful to the frontend, since it can now present feedback to the user and avoid entering an inconsistent state.

However, if an incorrect mount is provided (e.g. with the wrong port), it takes 30 seconds for it to be rejected. On the frontend, this translates to the user waiting for 30 seconds before they receive the following feedback: 

```
{"error":"Invalid server and / or port specified.","errorDetail":"Timed out after 30000 ms while waiting for a server that matches PrimaryServerSelector. Client view of cluster state is {type=UNKNOWN, servers=[{address=ds045089.mongolab.com:45087, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused}}]"}
```

It this something that can be improved? Ideally it would fail a lot sooner, but if that's not possible, we should probably open a ticket on the frontend to show some indication to the user that we are validating the mount (since it just looks like the app got wedged).

**Comment by jdegoes** [comment]
Looks like we can [tweak the timeout](http://stackoverflow.com/questions/6520439/how-to-configure-mongodb-java-driver-mongooptions-for-production-use) in the driver. I do think that 30 seconds is an unreasonably long time to wait. Perhaps 5 or 10 seconds at the outset. Of course, the front-end should display the twirly loading sign while the dialog is blocked so the user knows the connection is being tested; that will help, but 30 seconds is still a long time...

**Comment by mossprescott** [comment]
This is apparently the default for the MongoDB Java driver (see [this javadoc](http://api.mongodb.org/java/current/com/mongodb/MongoClientOptions.html#getServerSelectionTimeout--)). We currently provide no mechanism to override these settings.

I'll change it to 5 seconds for now. We may at some point have to make it configurable.

**Comment by jonsterling** [comment]
@mossprescott @jdegoes thanks a lot!
